### ISSUE TITLE
[BUG] - Crash on startup while initializing 'production'

### ISSUE THREAD

**Issue by jaroslawp** [m4dm4rtig4n/myelectricaldata#135]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Sometimes the addon does not initialize properly - see the error below. after a restart (or few) it initializes properly.

**Configuration**
cycle: 3600
debug: true
enedis_gateway:
  XXXXXXXXXXXXXXXXXX:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1841
    consumption_price_hc: 0.1470
    consumption_price_hp: 0.1841
    offpeak_hours: null
    plan: HP/HC
    production: true
    production_detail: true
    refresh_addresses: false
    refresh_contract: false
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: core-mosquitto
  password: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'addons'
wipe_cache: false

**Type d'installation**
HassIO

**Version :  0.7.7-3**

** log **
2022-11-20 08:30:00.399495 - DEBUG :  MQTT Send : enedis_gateway/XXXXXXXXXXXXXXXXXXX/production/current_year/dateEnded => 2022-11-20
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 365, in run
    ha_discovery_production = day.getDaily(headers, cur, con, client, pdl, pdl_config, "production",
  File "/app/daily.py", line 48, in getDaily
    current_value = int(value["value"])
TypeError: string indices must be integers
[08:30:00] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by m4dm4rtig4n** [comment]
Hello, @jaroslawp,
I advise you to wait for 0.8.0 which should be available soon and fix a lot of bugs.
