### ISSUE TITLE
[BUG] - daily quota is not resetted at midnight

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#137]
version 0.8.0
at midnight the limit of 50 is not resetted
So my base is never updated
Phil

**Comment by m4dm4rtig4n** [comment]
Fix normalement :)

**Comment by pbranly** [comment]
Non:
J’ai télécharge la dernière dev ce matin.
Dans les logs je suis en dépassement des 150 .( ce n’est plus 50)
Mais sur le site web:
pdl 1 326/50 et pdl2 622/50
Phil

**Comment by pbranly** [comment]
Hi
With the tonight 0.8.0-dev, the limit of 150 is now correct on the web site .
I see in the logs quite nothing because program stops at the beginning. Did you implement the feature that prevents any further download in case limit is overtaken ? If yes it works. Fine 
But I cannot make further tests as my limit of 150 was burned during the night with previous 0.8.0 version
Please reset my counter 

phil

**Comment by pbranly** [comment]
will see to morrow

**Comment by pbranly** [comment]
it seems and work
