### ISSUE TITLE
version 0.8.1: detailed data are incomplete

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#144]
Hi
There is a big period where all the detailed (hourly) datas are missing in influx
![2022-11-24_16-52](https://user-images.githubusercontent.com/22018509/203827669-4c954df3-e1b2-473f-90ba-fe9e6ff942d4.png)
those datas are missing as well in the cache.db data base:
![2022-11-24_17-00](https://user-images.githubusercontent.com/22018509/203827807-0255941d-0b2d-4537-8012-f44ddbb9b575.png)
While they are available in Enedis (see excel file for the same period)
![2022-11-24_17-04](https://user-images.githubusercontent.com/22018509/203827928-604e3bc2-2359-46e0-987f-56c30e95cbbb.png)

For information, those datas were available in an old influxdb database got from early versions of the myelectricaldata program
![2022-11-24_16-54](https://user-images.githubusercontent.com/22018509/203828121-2e592917-c017-49e8-b392-0db16a0d97c3.png)

**Comment by cvalentin-dkt** [comment]
Reset du cache => OK
