### ISSUE TITLE
[BUG] - [0.8.2-dev] Pb dans le tri du tableau de l'UI

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#145]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Dans le tableau "Mes données journalières, les tri des colonnes se fait en texte et non sur les nombres. Par exemple un tri croissant sur la colonne consommation donne :
- 10040
- 100410
- 10072

![image](https://user-images.githubusercontent.com/682743/203938929-4ec11b9b-3317-43dc-a68c-e397ae5f610a.png)

**Configuration**
Il me faut la partie enedis_gateway de votre config.yml, sans les PDL et Token.

**Type d'installation**
Docker

**Version : 0.8.2-dev**

**Comment by cvalentin-dkt** [comment]
Ou j'ai remarqué quelques soucis déjà, je vais virer les W (et les spécifier dans le titre) car ca fait foirer le tri du tableau

**Comment by m4dm4rtig4n** [comment]
Fix sur la 0.8.3-dev https://github.com/m4dm4rtig4n/myelectricaldata/pull/147/commits/2ba3d77f6c5b0842536aadd29334d4e7a187112c#diff-52539b94c626357992c4b585f51f2cbb37b0a458791cb5aed09767bdbfb1324b qui ne va pas tarder à sortir.

**Comment by m4dm4rtig4n** [comment]
La version est en ligne !
