### ISSUE TITLE
[HELP] - ENHANCEMENT question on limiting the history for collecting data

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#152]
From version 0.8.x
At present the integration collects data 'daily' for 1095 days back and for 'detail' 729 days
Not everyone is interested in this enormous history and added to that, if you donot have that history because you have a new account with Enedis, the integration continuous to search for that data even though it will not be there, every time eating into the quota of calls per day
Suggestion: add some params, e.g. detail_days / daily_days that can be smaller than above numbers and which users can define in config.yaml (at present these are in config.py but that is out of reach unless you know how to get there and modify it).
I am happy to spend some time on it but I would like to know:
- are you OK to add this type of funtionality
- can it be part of config.yaml and then 'where', i.e. if part of the usage point it should then also go the db?
- have you already thought about it and a possible structure in mind that I can take over?

**Comment by m4dm4rtig4n** [comment]
En fait actuellement j'utilise "last_activation_date" qui est renvoyer par Enedis pour fixer la date maximun.
Sauf que j'ai l'impression que la donnée renvoyer par cette date est assez aléatoire du style :
- J'ai des utilisateurs (comme moi) qui récupére bien la date où je eménagé dans la maison.
- Chez d'autre utilisateurs, c'est la date du dernier changement de contrat (alors que perso j'ai 5 fois de contrat depuis la date remonter par l'API d'enedis)
- D'autre la date de l'ancien propriétaire...
- ...

Je vais voir pour ajouter un champ date "maximun" de récupération qui sera avec la valeur par défaut qui sera la valeur envoyer par les API avec possibilité de la surchager comme les HC/HP.

**Comment by vingerha** [comment]
Donc, chez moi 'last_activation_date'  (dans le bdd) est 2017-05-23 ce qui est curieux car nous avons déménagé fin 2016 et l'autre changement du contrat était en 2021 (HP/HC > BASE). Nous étions toujours chez EDF.
Pour 'max' il faut avoir deux 'max' car mes données détaillées n'existent que depuis Linky (mai 2021) et journaliers depuis mai 2020.

**Comment by m4dm4rtig4n** [comment]
C'est juste un des retours "curieux" parmis tant d'autre avec Enedis...

**Comment by m4dm4rtig4n** [comment]
La feature sera dispo sur la 0.8.4.

**Comment by m4dm4rtig4n** [comment]
@vingerha je te laisse tester la fonctionnalité dans la 0.8.5 et tiens moi au jus :)

**Comment by vingerha** [comment]
J'ai fait deux runs dans 10 min., les logs ajouté....pas 100% sûre mais je pense que ç'a pas marché
call_number 1: 13 
call_number 2: 82
error 'base' encore là (tu le sait) :)
bdd, je ne sais pas si t'as envisagé de l'utiliser mais 'vide'
![image](https://user-images.githubusercontent.com/44190435/205290546-ff56f51c-538c-4006-9c98-0873c8c457bd.png)
[_myelectricaldata_dev_logs_8.2.5_dev_run1.txt](https://github.com/m4dm4rtig4n/myelectricaldata/files/10140987/_myelectricaldata_dev_logs_8.2.5_dev_run1.txt)
[_myelectricaldata_dev_logs_8.2.5_dev_run2.txt](https://github.com/m4dm4rtig4n/myelectricaldata/files/10140989/_myelectricaldata_dev_logs_8.2.5_dev_run2.txt)

**Comment by vingerha** [comment]
et...c'est 085 que j'ai testé

**Comment by m4dm4rtig4n** [comment]
Tu n'a pas renseigner les date dans la configuration du point de livraison aussi ?
Si tu ne configure pas les dates, je reprend la valeur récupéré dans ton contrat par défaut.

J'ai ajouter 4 paramêtres dans le config.yaml des points de livraison :
* consumption_max_date
* consumption_detail_max_date
* production_max_date
* production_detail_max_date

Tu peut également définir les date directement depuis l'IHM : 

![image](https://user-images.githubusercontent.com/7872518/205294196-0f42a85f-b8f5-4c80-9d5c-84b221b78363.png)

![image](https://user-images.githubusercontent.com/7872518/205294189-5a5eb288-580e-4cc2-beb1-a47af7aac24c.png)

**Comment by m4dm4rtig4n** [comment]
Valider sur Discord :)
