### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by data-source** [m4dm4rtig4n/myelectricaldata#153]
**Description du bug**
DEBUG : {'error_code': True, 'detail': {'message': {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}}}

Impossible de faire passer le token. 4 nouveaux tokens générés, ' ou " pareil, nouveau fichier de conf tout neuf, conversions, validations yaml en ligne, rien n'y fait. 

/usr/local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

**Configuration**
enedis_gateway:
  "00000000000":
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.18971
    #consumption_price_hc: 0
    #consumption_price_hp: 0.157
    #offpeak_hours: null
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
    token: "token"

**Type d'installation**
HassIO 

**Version : 0.7.7-3*

**Comment by m4dm4rtig4n** [comment]
Je ne fait plus de support sur la 0.7.X, tu peut basculer sur la 0.8.3-dev si tu le souhaite qui est encore en dev mais stable.
Encore quelques petits bug persiste mais je suis sur le sujet.
