### ISSUE TITLE
[BUG] - Unitées erronnées dans la table influxdb details

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#159]
La table Consumption_details" est remplie dans Influx avec les unités Wh, kWh et price alors que les valeurs correspondent à celles de Enedis en W pendant un intervalle de temps variable (10, 30, 60 mn)

la table devrait etre remplie soit:
- en W ou/et kW charge à l'utilisateur de calculer ses Wh ou kWh en les pondérant du rapport de intervalle de temps / 60 mn (comme dans enedisgateway2mqtt)
- en Wh et/ou kWh en pondérant chaque valeur de l'intervalle de temps/60 mn

Nota : la colonne price doit être également erronée
 
exemple sur une plage de date quelconque :
Table téléchargée sur Enedis:

2022-05-02T08:00:00+02:00 | 228 |  
2022-05-02T08:30:00+02:00 | 442 |  
2022-05-02T09:00:00+02:00 | 2024 |  
2022-05-02T09:30:00+02:00 | 1432 |  
2022-05-02T10:00:00+02:00 | 688 |  
2022-05-02T10:30:00+02:00 | 234 |  

Table dans Influxdb:
![2022-12-02_08-56](https://user-images.githubusercontent.com/22018509/205243992-2eb45753-6219-4273-b2a3-89ccef5a5588.png)

**Type d'installation**
Docker

**Version : 0.8.4**

**Comment by m4dm4rtig4n** [comment]
A tester, mais je viens de fix ca dans la 0.8.5-dev

**Comment by m4dm4rtig4n** [comment]
Tt est bon dans le cochon!
