### ISSUE TITLE
[BUG] - le fichier app/VERSION n'est pas mis à jour

### ISSUE THREAD

**Issue by evenisse** [m4dm4rtig4n/myelectricaldata#167]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
le fichier app/VERSION n'est pas mis à jour. Il faudrait le mettre à jour lors de l'exécution du workflow de release

**Configuration**

**Type d'installation**
Docker

**Version : 0.8.7**

**Comment by m4dm4rtig4n** [comment]
Fait dans la 0.8.8-dev.
