### ISSUE TITLE
[HELP] - Afficher la version dans l'UI

### ISSUE THREAD

**Issue by Jeoffreybauvin** [m4dm4rtig4n/myelectricaldata#169]
J'ai beau chercher, je ne trouve pas la version de MyElectricalData dans l'UI. Ce serait bien de la rajouter.

**Type d'installation**
Docker

**Version : 0.8.8-dev**

**Comment by m4dm4rtig4n** [comment]
Je suis justement en train de le faire :D

**Comment by m4dm4rtig4n** [comment]
Ca pop dans la dernière release 0.8.8-dev :)
![image](https://user-images.githubusercontent.com/7872518/205436336-01184cde-e264-4a32-9a4b-ff86759bee04.png)
