### ISSUE TITLE
[BUG] - Limitation à 2 chiffres après la virgule sur le calcul des prix 

### ISSUE THREAD

**Issue by chatbubu2** [m4dm4rtig4n/myelectricaldata#174]
Bonjour,
Voici le problème rencontré : 
Dans la table consumption_detail, la colonne "price" on retrouve le prix pour chaque consommation mais celui-ci est limité à 2 chiffres après la virgule, cette limitation génère des erreurs de calcul lorsqu'on fait des sommes sur les colonnes dans Graphana.

Dans mon cas, l'électricité est à 0.1740 du Kwh. et voici un exemple de quelques tickets pour la journée du 26/11 que j'ai dans  consumption_detail
04:00; 1.16Kwh; 0.20€ ==> On devrait avoir 1.16 X 0.1740 = 0,20184
04:30; 1.18Kwh; 0.20€ ==> On devrait avoir 1.18 X 0.1740 = 0,20532
05:00; 0.85Kwh; 0.14€ ==> On devrait avoir 0.85 X 0.1740 = 0,1479

Ca ne fait pas beaucoup d'écart de valorisation mais en faisant un somme sur l'ensemble des tickets de  l'année ça commence à faire des sous :-)

**Configuration**
myelectricaldata:
  MASQUE:
    enable: 'true'
    token: MASQUE
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1740'
    consumption_price_hc: '0.1740'
    consumption_price_hp: '0.1740'
    consumption_max_date: "2021-04-01"
    consumption_detail_max_date: "2021-04-01"
    offpeak_hours_0: ""
    offpeak_hours_1: ""
    offpeak_hours_2: ""
    offpeak_hours_3: ""
    offpeak_hours_4: ""
    offpeak_hours_5: ""
    offpeak_hours_6: ""
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: ""
    production_detail_max_date: ""
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
HassiO 

**Version : 0.8.7**

**Comment by m4dm4rtig4n** [comment]
Ca arrivera dans les 0.8.8.

**Comment by chatbubu2** [comment]
Top!, merci pour ce correctif.
