### ISSUE TITLE
Remonter la puissance max

### ISSUE THREAD

**Issue by m4dm4rtig4n** [m4dm4rtig4n/myelectricaldata#187]
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/66

**Comment by buddy31130** [comment]
Bonsoir,
Il me semble que ce que @navycrow  voulait parler est le pic de puissance max quotidien qu'Enedis donne chaque jour

**Comment by Skuair** [comment]
Bonjour, également intéressé par la puissance max soutirée journalière.

**Comment by m4dm4rtig4n** [comment]
![image](https://user-images.githubusercontent.com/7872518/208326644-1b0efa42-728b-4107-abc7-08b26a21e109.png)

**Comment by m4dm4rtig4n** [comment]
Ca sortira avec la 0.8.11.
