### ISSUE TITLE
[BUG] - Consommation J-1 indisponible

### ISSUE THREAD

**Issue by buddy31130** [m4dm4rtig4n/myelectricaldata#188]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Bonsoir, 
Je ne sais pas si c'est le cas d'autres personnes, mais je n'ai plus accès aux données de consommation à J-1. J'ai toutes les données qu'à partir de J-2. Les données sont en accord avec celles d'Enedis.
Je dis que je n'ai plus accès car avec EnedisGateway2MQTT, je n'avais pas ce soucis.

Merci :)

**Configuration**
cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: enedisMQTT:linky
  org: "-"
  bucket: "enedisMQTT/autogen"
  method: asynchronous
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "XX"
  password: "XX"
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  'PDL':
    enable: 'true'
    token: "ToKeN"
    name: Maison
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_hc: '0.13848'
    consumption_price_hp: '0.18594'
    offpeak_hours_0: 22H24-6H24
    offpeak_hours_1: 22H24-6H24
    offpeak_hours_2: 22H24-6H24
    offpeak_hours_3: 22H24-6H24
    offpeak_hours_4: 22H24-6H24
    offpeak_hours_5: 22H24-6H24
    offpeak_hours_6: 22H24-6H24
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
HassIO

**Version : X.X.X**
 2022.11.5

**Comment by buddy31130** [comment]
![image](https://user-images.githubusercontent.com/83547288/206293632-e370487d-69bd-447a-b1d9-fe9426c0f249.png)

**Comment by m4dm4rtig4n** [comment]
Fix sur la 0.8.8 qui ne va pas tarder à pop :
https://github.com/m4dm4rtig4n/myelectricaldata/issues/173
