### ISSUE TITLE
[BUG] - Export INFLUXDB KO

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#221]
**Description du bug**

2022-12-13 10:48:13.292 -     INFO :  [22149782812123] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2022-12-13 10:48:13.292 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-13 10:48:13.326 -     INFO :   - 2022-12
Traceback (most recent call last):
  File "/app/models/jobs.py", line 171, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
  File "/app/models/export_influxdb.py", line 34, in daily
    app.INFLUXDB.write(
  File "/app/models/influxdb.py", line 167, in write
    self.write_api.write(bucket=self.bucket, org=self.org, record=record)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 374, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 372, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/write_api.py", line 483, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Request-Id': '42a34878-7acb-11ed-a3d4-0242ac1e2103', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Error': 'partial write: field type conflict: input field "Wh" on measurement "consumption" is type float, already exists as type integer dropped=1', 'X-Influxdb-Version': '1.8.10', 'X-Request-Id': '42a34878-7acb-11ed-a3d4-0242ac1e2103', 'Date': 'Tue, 13 Dec 2022 09:48:13 GMT', 'Content-Length': '154'})
HTTP response body: {"error":"partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
2022-12-13 10:48:13.383 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-13 10:48:13.383 -    ERROR : 
2022-12-13 10:48:13.383 -    ERROR :  Erreur lors de l'exportation des données dans InfluxDB
2022-12-13 10:48:13.384 -    ERROR :  (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Request-Id': '42a34878-7acb-11ed-a3d4-0242ac1e2103', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Error': 'partial write: field type conflict: input field "Wh" on measurement "consumption" is type float, already exists as type integer dropped=1', 'X-Influxdb-Version': '1.8.10', 'X-Request-Id': '42a34878-7acb-11ed-a3d4-0242ac1e2103', 'Date': 'Tue, 13 Dec 2022 09:48:13 GMT', 'Content-Length': '154'})
HTTP response body: {"error":"partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
2022-12-13 10:48:13.384 -    ERROR : 
2022-12-13 10:48:13.384 -    ERROR : 

**Configuration**

cycle: 14400 # 4H
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: haha:haha
  org: "-"
  bucket: "homeassistant/autogen" 
  asynchronous: "false"
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: mosquitto
  port: 1883
  username: "login"
  password: "toto"
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "22149687564567":
    enable: "true"
    token: gGvMzy_hk3GIGYGYGOUYGUGF
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.1679" ## 01/01/23 => 0,1740
    consumption_price_hc: "0.1422" ## 01/01/23 => 0,1330
    consumption_price_hp: "0.1769" ## 01/01/23 => 0,1936
    consumption_max_date: "2021-07-03"
    consumption_detail_max_date: "2021-07-03"
    offpeak_hours_0: 01H36-8H06;12H06-13H36 # LUNDI
    offpeak_hours_1: 01H36-8H06;12H06-13H36 # MARDI
    offpeak_hours_2: 01H36-8H06;12H06-13H36 # MERCREDI
    offpeak_hours_3: 01H36-8H06;12H06-13H36 # JEUDI
    offpeak_hours_4: 01H36-8H06;12H06-13H36 # VENDREDI
    offpeak_hours_5: 01H36-8H06;12H06-13H36 # SAMEDI
    offpeak_hours_6: 01H36-8H06;12H06-13H36 # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"

**Type d'installation**
HassIO

**Version : 0.8.10**

**Comment by evenisse** [comment]
Il semblerait qu'influxdb conserve des informations sur d'anciennes données et que même un wipe_influxdb ne peut les supprimer. La solution trouvée pour le moment est de se créer une nouvelle base influxdb

**Comment by floow77** [comment]
Merci @evenisse, je vais créer une nouvelle bdd

**Comment by airvb** [comment]
Bonjour !
Un nouveau bucket , pas la base complète ?

**Comment by evenisse** [comment]
oui, un nouveau bucket

**Comment by airvb** [comment]
Si cela peut aider :
`Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.4.0', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 13 Dec 2022 10:41:59 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"Wh\" on measurement \"consumption\" is type float, already exists as type integer dropped=1"}
`

**Comment by m4dm4rtig4n** [comment]
@airvb tu as encore le soucis avec un nouveau bucket ?

**Comment by evenisse** [comment]
Ce n'est pas un problème avec influxdb mais le cache. Tu dois avoir une 'vieille' version du schéma SQL pour la base de cache. Supprime le fichier cache.db et redémarre.

**Comment by airvb** [comment]
Bien vu, 
J'ai effacé le cache.db et c'est reparti...
Mais le problème de consentement est revenu...
Je vais tenter :+
- effacer le cache
- effacer et recréer le bucket
- refaire les consentement
- Maj du config.yaml avec le nouveau token.

Keep in touch !

**Comment by YNK22** [comment]
Dans ton fichier de conf je vois la ligne 
`asynchronous: "false"` mais depuis la dernière maj il faut remplacer cette ligne par `method: synchronous` (voir fichier config.yaml sur le github)

**Comment by m4dm4rtig4n** [comment]
> Dans ton fichier de conf je vois la ligne `asynchronous: "false"` mais depuis la dernière maj il faut remplacer cette ligne par `method: synchronous` (voir fichier config.yaml sur le github)

Ce n'est pas obligatoire, si il ne détecte pas le param "method", je set "synchronous" automatiquement.

**Comment by airvb** [comment]
Bsr , 
C'est revenu Tout est ok
