### ISSUE TITLE
[BUG] - Pas de données des 4 derniers jours

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#222]
**Description du bug**
Mon sensor.myelectricaldata_221567645874 ne remonte pas les données des 3 derniers jours:

numPDL: 221567645874 
activationDate: 2021-07-03 00:00:00
lastUpdate: 2022-12-13 10:12:11
timeLastCall: 2022-12-13 10:12:11
yesterdayDate: 2022-12-12
yesterday: 0
yesterdayLastYearDate: 2021-12-13
yesterdayLastYear: 0
daily: 0, 0, 0, 0, 33.8, 49.2, 49.8
current_week: 132.8
last_week: 216.6
**day_1: 0
day_2: 0
day_3: 0
day_4: 0**
day_5: 33.8
day_6: 49.2
day_7: 49.8

**Configuration**

cycle: 14400 # 4H
debug: true
wipe_influxdb: false
home_assistant:
enable: true
discovery: true
discovery_prefix: homeassistant
influxdb:
enable: true
hostname: influxdb
port: 8086
token: haha:haha
org: "-"
bucket: "homeassistant/autogen"
asynchronous: "false"
batching_options:
batch_size: 1000
flush_interval: 1000
jitter_interval: 0
retry_interval: 5000
max_retry_time: 180_000
max_retries: 5
max_retry_delay: 125_000
exponential_base: 2
mqtt:
enable: true
hostname: mosquitto
port: 1883
username: "login"
password: "toto"
prefix: myelectricaldata
client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
retain: true
qos: 0
myelectricaldata:
"22149687564567":
enable: "true"
token: gGvMzy_hk3GIGYGYGOUYGUGF
name: "Maison"
addresses: "true"
cache: "true"
consumption: "true"
consumption_detail: "true"
consumption_price_base: "0.1679" ## 01/01/23 => 0,1740
consumption_price_hc: "0.1422" ## 01/01/23 => 0,1330
consumption_price_hp: "0.1769" ## 01/01/23 => 0,1936
consumption_max_date: "2021-07-03"
consumption_detail_max_date: "2021-07-03"
offpeak_hours_0: 01H36-8H06;12H06-13H36 # LUNDI
offpeak_hours_1: 01H36-8H06;12H06-13H36 # MARDI
offpeak_hours_2: 01H36-8H06;12H06-13H36 # MERCREDI
offpeak_hours_3: 01H36-8H06;12H06-13H36 # JEUDI
offpeak_hours_4: 01H36-8H06;12H06-13H36 # VENDREDI
offpeak_hours_5: 01H36-8H06;12H06-13H36 # SAMEDI
offpeak_hours_6: 01H36-8H06;12H06-13H36 # DIMANCHE
plan: HC/HP
production: "false"
production_detail: "false"
production_price: "0.0"
production_max_date: "2021-06-01"
production_detail_max_date: "2021-06-01"
refresh_addresse: "false"
refresh_contract: "false"

**Type d'installation**
HassIO

**Version : 0.8.10**

**Comment by m4dm4rtig4n** [comment]
Il y avait un soucis sur la passerelle depuis quelques jours,
J'ai push un fix ce midi mais il est nécéssaire de refaire un consentement.

**Comment by buddy31130** [comment]
Personnellement, je n'ai plus les détails HP HC depuis 6 jours. J'ai par contre le décompte total par jour.

**Comment by m4dm4rtig4n** [comment]
@buddy31130  
Sur MQTT ? Home Assistant ?

**Comment by buddy31130** [comment]
@m4dm4rtig4n sur Home Assistant et dans l'application 
![image](https://user-images.githubusercontent.com/83547288/207959267-5b23ba7c-5bf2-4737-8bad-fc3f894c9ebd.png)

**Comment by m4dm4rtig4n** [comment]
@buddy31130 et tu peu me link ta config ?

**Comment by buddy31130** [comment]
@m4dm4rtig4n oui :) 
`cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: enedisMQTT:linky
  org: "-"
  bucket: "enedisMQTT/autogen"
  method: synchronous
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "XX"
  password: "XX"
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  'XXXX':
    enable: 'true'
    token: "XXXXX="
    name: Maison
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_hc: '0.13848'
    consumption_price_hp: '0.18594'
    offpeak_hours_0: 22H24-6H24
    offpeak_hours_1: 22H24-6H24
    offpeak_hours_2: 22H24-6H24
    offpeak_hours_3: 22H24-6H24
    offpeak_hours_4: 22H24-6H24
    offpeak_hours_5: 22H24-6H24
    offpeak_hours_6: 22H24-6H24
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
`

**Comment by m4dm4rtig4n** [comment]
@buddy31130 et la donnée est dispo chez Enedis ?
Ton relever horaire est bien toujours actif ?

**Comment by buddy31130** [comment]
@m4dm4rtig4n de manière inexpliquée, le service était desactivé depuis 1 mois sur le site ENEDIS alors que j'avais le détail la semaine dernière... je reviendrais dire si ça marche :)

**Comment by m4dm4rtig4n** [comment]
Je clos dans tt les cas l'issue comme le soucis de @floow77 est réglé.
