### ISSUE TITLE
[BUG] - Error 401

### ISSUE THREAD

**Issue by Pepeanuts** [m4dm4rtig4n/myelectricaldata#224]
**Description du bug**
Suite nouveau consentement pour myelectricaldata : 
`"detail": "Soucis au niveau des consentements, merci de les renouveler sur https://www.myelectricaldata.fr - Code d'erreur : 401 (cf. F.A.Q pour les codes d'erreurs)"`
Alors que la collecte est bien activée 

**Configuration**
![image](https://user-images.githubusercontent.com/73701866/207305176-2e329bff-d46b-4fe4-bbec-7afb94d8dd3d.png)

**Type d'installation**
 HassIO

myEnedis 2.0.2
HA 2022.12.3

**Comment by buchnoun** [comment]
J'ai le même problème.
J'ai redemandé le consentement, update mon token et pareil err 401
Home Assistant 2022.12.4 - OS 9.4

**Comment by m4dm4rtig4n** [comment]
Il y avait un soucis sur la passerelle depuis quelques jours,
J'ai push un fix ce midi mais il est nécéssaire de refaire un consentement.

**Comment by YNK22** [comment]
J'avais le même soucis, j'ai refais mon consentement et l'erreur a disparu.

Je suis sur la dernière MAJ 0.8.10-Test et sur HassOS

**Comment by m4dm4rtig4n** [comment]
@Pepeanuts tu as encore le soucis ?

**Comment by Pepeanuts** [comment]
Je viens de refaire une demande et cette ça semble bon, à clore!
