### ISSUE TITLE
[BUG] - Erreur au lancement config.yaml 0.8.10

### ISSUE THREAD

**Issue by GeoMCE** [m4dm4rtig4n/myelectricaldata#225]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Suite à la MaJ en 0.8.10, le module ne se lance plus

MyElectricalData
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.12.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/enedisgateway2mqtt/config.yaml'
TZ='Europe/Paris'
mqtt_autodiscover='true'
verbose='true'
/etc/cont-init.d/01-custom_script.sh: executing
[18:01:13] INFO: Execute /config/enedisgateway2mqtt.sh if existing
[18:01:13] INFO: ... no script found
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[18:01:13] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[18:01:13] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
[18:01:15] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
/config/enedisgateway2mqtt/config.yaml
  27:17     warning  too many spaces before colon  (colons)
  50:56     error    no new line character at the end of file  (new-line-at-end-of-file)
[18:01:15] FATAL: Config file has an invalid yaml format. Please check the file in /config/enedisgateway2mqtt/config.yaml. Errors list above. You can check yaml validity with the online tool yamllint.com
/etc/cont-init.d/99-run.sh: exiting 1

Donc, a priori, une erreur avec mon fichier config.yaml. Je ne l'ai pas modifié - à l'exception du renouvellement du consentement - et j'ai vérifié sa structure avec yamllint, sans avoir d'erreur retourné

**Configuration**
Dans le doute, le config en entier

```
cycle: 14400
debug: false
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  asynchronous: 'false'
  bucket: myelectricaldata
  enable: false
  host: influxdb
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
mqtt:
  client_id: myelectricaldata
  hostname: core-mosquitto
  enable: true
  host: 127.0.0.1
  password: XXXXXXXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: Mqtt
myelectricaldata:
  XXXXXXXXXXX :
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: 0
    consumption_price_hc: 0.1499
    consumption_price_hp: 0.2103
    enable: true
    offpeak_hours_0: 0H52-6H52;12H22-14H22
    offpeak_hours_1: 0H52-6H52;12H22-14H22
    offpeak_hours_2: 0H00-23H59
    offpeak_hours_3: 0H52-6H52;12H22-14H22
    offpeak_hours_4: 0H52-6H52;12H22-14H22
    offpeak_hours_5: 0H00-23H59
    offpeak_hours_6: 0H00-23H59
    plan: HC/HP
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Type d'installation**
HassIO

**Version : 0.8.10**

**Comment by buddy31130** [comment]
tu as vérifié sur le site : https://jsonformatter.org/yaml-validator ?

**Comment by GeoMCE** [comment]
merci pour la proposition mais pas de pb détecté... mais pb résolu : il fallai juste que je lise bien le msg d'erreur. Je n'avais de saut de ligne à la fin ...
