### ISSUE TITLE
[HELP] - Grafana support pour myelectricalData

### ISSUE THREAD

**Issue by gregtux77** [m4dm4rtig4n/myelectricaldata#231]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Support Grafana**

Avec la version actuel je n'arrive pas un generer un Dashbord interessant ( en reprennant celui indiqué dans le REadme)
par exemple je ne retrouve pas "consumption_load_curve" , pouvez vous remettre un exmple grafana? 
Merci ! 

**Type d'installation**
Docker, Linux AMR RPI4 
influx :1.8.10
Grafana 9.3.1

**Version : 0.8.0**

**Comment by geobar78** [comment]
Je te partage mon dashboard qui est prêt pour 2023
base DATABASE.RETENTION 
[My Electrical Data-1671193298751.zip](https://github.com/m4dm4rtig4n/myelectricaldata/files/10245752/My.Electrical.Data-1671193298751.zip)

**Comment by geobar78** [comment]
ça donne ça 

![image](https://user-images.githubusercontent.com/75928935/208099481-cd3b3153-9ae9-4f0f-825f-d138f5e411e9.png)

![image](https://user-images.githubusercontent.com/75928935/208099536-b3df92d9-9115-40d3-976e-7c1d44cffd65.png)


![image](https://user-images.githubusercontent.com/75928935/208099593-c228fcd7-b1e4-48ed-a7a3-ba7abebb50ee.png)

**Comment by gregtux77** [comment]
super grand merci ! 
j ai quelques modifications a faire mais cela fonctionne !

**Comment by m4dm4rtig4n** [comment]
@geobar78 le plus simple je pense est que tu host ton template sur Github, et je mettrais une lien dans le readme :)
Sinon pour les update ca va vite devenir relou à maintenir :)

**Comment by geobar78** [comment]
@m4dm4rtig4n ça marche j'essaye de faire ça et reviens quand c'est prêt

**Comment by geobar78** [comment]
@m4dm4rtig4n Voilà je pense que ça doit être ça 

https://github.com/geobar78/Myelectricaldata-Graphana-Dashbord

Après je suis vraiment pas un expert de Graphana ni en informatique, j'ai simplement modifié ton dashboard pour que les pannels tapent dans la bonne influxdb, ça m'a pris une journée pour te dire ;-)

**Comment by geobar78** [comment]
@m4dm4rtig4n je n'arrive plus à retrouver ton tuto pour graphana, à l'époque tu avais fais une liste des choses à faire (voire des pluggins à ajouter) qui m'avait permis de monter le dashbord. si tu l'as encore sous la main je pourrais rajouter le lien sur mon readme.

**Comment by geobar78** [comment]
@m4dm4rtig4n c'est bon j'ai retrouvé 

[forum.hacf.fr/t/enedis-gateeway/868](https://forum.hacf.fr/t/enedis-gateway/868)

tu me permets d'y copier/coller la partie sur graphana ?

**Comment by m4dm4rtig4n** [comment]
oui fait toi plaisir :)

**Comment by airvb** [comment]
Quelqu’un s"est lancé avec influx v 2.0 ?

**Comment by evenisse** [comment]
@airvb il y en a sur le discord. Il faudra qu'on les rapatrie par ici.

**Comment by vingerha** [comment]
> Quelqu’un s"est lancé avec influx v 2.0 ?
Oui....en flux aussi ... en tant que vieux SQL pas si facile mais pas mal.
https://discord.com/channels/517999856116039698/1051111225569845268

**Comment by m4dm4rtig4n** [comment]
J'ai crée une page dédiée dans le wiki : 
https://github.com/m4dm4rtig4n/myelectricaldata/wiki/30.-Grafana
Si vous avez d'autre dashbord go me crée une autre issue avec le liens + un petit screen svp :)
