### ISSUE TITLE
[FEATURES] - Compte ENEDIS professionnel, impossible d'accéder au PDL

### ISSUE THREAD

**Issue by noiwid** [m4dm4rtig4n/myelectricaldata#235]
Bonjour,
Je souhaite utiliser votre add'on à mon bureau, je n'y parviens malheureusement pas.

L'URL qui permet de demander le consentement à ENEDIS pour la transmission des données semble spécifique aux comptes de particuliers :
`https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize?client_id=XXXXX&duration=P36M&response_type=code`
 
L'accès au compte pro se fait via des URL's sur le domaine 
`https://mon-compte-professionnel.enedis.fr/...`
 
En remplaçant particulier par professionnel sur l'URL dataconnect, on tombe malheureusement sur une 404.
Savez-vous si une URL dataconnect existe pour les comptes pro ?

Merci d'avance pour votre retour.

**Comment by m4dm4rtig4n** [comment]
Hello @noiwid alors la aucune idée mais je doute que ce soit possible.
Je vais poser la question directement à Enedis.

**Comment by m4dm4rtig4n** [comment]
Je viens d'avoir le retour d'Enedis qui me dit que ce n'est malheuresement pas possible pour l'instant.
Et que ce n'est pas dans les todo.
