### ISSUE TITLE
[BUG] - 0.8.11 le nouveau tableau puissance Max est en W kW au lieu de Va kVA

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#238]
Les infos de ENEDIS pour ces valeurs sont en kVA .
Le nouveau tableau disponible dans la version 0.8.11 donne des valeurs en W et kW
Propositions de modification : changer le titre des colonnes

**Comment by m4dm4rtig4n** [comment]
C'est déjà fait et sera dans la prochaine release.

**Comment by pbranly** [comment]
this issue is not completed in the today beta 5 release
