### ISSUE TITLE
[FEATURES] - ajouter un sensor détail de consommation horaire sur modèle des sensors "Saniho"

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#241]
Il est possible de créer une carte apexcharts-card avec un sensor provenant de l'intégration de Saniho fournissant un historique horaire sur j-2.
L'intégration actuelle de myelectricaldata ne fournit pas ce sensor.
Les informations nécessaire sont les suivantes:

![image](https://user-images.githubusercontent.com/22018509/208919311-835dcbb9-ba1c-44b4-afb1-660a6938e4d2.jpeg)

![image](https://user-images.githubusercontent.com/22018509/208919342-b83b85c8-2cf6-483b-a459-733654cc0f9d.jpeg)

![image](https://user-images.githubusercontent.com/22018509/208919390-f15f3dca-671a-4b5e-9ca7-6a0b1e3855a3.jpeg)

Et la carte finale que cela donne 😀 

![image](https://user-images.githubusercontent.com/22018509/208919475-7cd486f5-d8d0-4ef4-a438-164e377d28b0.jpeg)

Nota: il y a aussi d'autres sensors donnant les détails HP, HC, production, etc ....
Phil

**Comment by m4dm4rtig4n** [comment]
Bon j'ai eu la réponse de Saniho et c'est pourri..
Il envoie les données avec 2j de delta en fait parce que HA ne propose pas de méthode pour envoyer de la donnée dans le passé...

**Comment by pbranly** [comment]
Effectivement .... pas évident

**Comment by m4dm4rtig4n** [comment]
Bah je peut le faire, mais du coup c'est pas si simple et je trouve pas ceci hyper utile du coup...

**Comment by pbranly** [comment]
L’utilité, c’est de pouvoir afficher un historique de consommation horaire.
Sinon on n’a que l’historique journalier 
Phil

**Comment by m4dm4rtig4n** [comment]
Simuler une donnée temps réel avec des données passé n'est pas pour moi une bonne pratique dans tt les cas.

Il y a d'autre méthode plus adapter au fonctionnement d'Home Assistant comme celle crée sur l'issue suivantes :
https://github.com/m4dm4rtig4n/myelectricaldata/issues/243
