### ISSUE TITLE
[BUG] - retour sur: la veille manquant 8.11 et (!) 8.11-beta6

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#244]
pareil soucis que hier avant d'avoir installé 8.11-beta6
- données visible dans enedis
- données peuvent être importé par le site
- pas des données dans cache.db, ni journalier, ni détails
- différent que hier: maintenant aussi pas le max puissances manquent
je joint le log de beta6, voir 8.11 dans l'autre issue que je vais ouvrir
[_myelectricaldata_logs_8_11_beta6.txt](https://github.com/m4dm4rtig4n/myelectricaldata/files/10292689/_myelectricaldata_logs_8_11_beta6.txt)

![image](https://user-images.githubusercontent.com/44190435/209290417-a938b748-617c-4da2-8d54-63df5c174a6e.png)
![image](https://user-images.githubusercontent.com/44190435/209290488-83097df8-331f-43f3-a73f-cfc9eb214e33.png)

**Comment by slider07210** [comment]
Bonjour,
Pour moi aussi les données ne remonte pas de la veille par contre je suis en 0.8.11-beta1.
Petite question très bête comment faire pour mettre à jour vers les releases beta notamment la beta 6 dans le supervisor ?
Merci par avance

**Comment by vingerha** [comment]
resolu avec 8.12-beta1
