### ISSUE TITLE
[BUG] - Données de la veille absentes

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#247]
**Description du bug**
Les données de la veille sont tout le temps à 0.

Extrait du sensor:
day_1: 0
day_2: 23.93
day_3: 26.25

**Type d'installation**
HassIO

**Version : 0.8.11-beta6**

**Comment by m4dm4rtig4n** [comment]
Résolue dans la 0.8.12.beta1.
