### ISSUE TITLE
[FEATURES] - Ajout d'un sensor production pour HA

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/myelectricaldata#251]
Ajouter dans homeassistant un sensor.myelectricaldata_production_pdl avec les mêmes infos que la conso comme ca on pourrait se servir directement du widget de sanhiho pour voir la production également.

**Comment by m4dm4rtig4n** [comment]
Ce sera disponible à partir de la 0.8.11-beta3.

**Comment by m4dm4rtig4n** [comment]
C'est en ligne dans la 0.8.12.
