### ISSUE TITLE
[FEATURES] - new attributes for card-linky

### ISSUE THREAD

**Issue by saniho** [m4dm4rtig4n/myelectricaldata#252]
@m4dm4rtig4n , pour information un nouvel attribut est necessaire à la prochaine card, il s'agit de : 
ServiceEnedis avec la valeur myElectricalData ou enedisGateway
ceci afin de faire afficher un message pour indeiquer qu'il faut penser à migrer vers myElectricData ;)

**Comment by cvalentin-dkt** [comment]
Ah cool thx, je l'ajouter coté client également :)

**Comment by m4dm4rtig4n** [comment]
J'ai ajouter l'attribue dans la 0.8.12-beta3.
