### ISSUE TITLE
[FEATURES] - Bouton pour vider le cache anterieur à une certaine date

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/myelectricaldata#254]
J'avais pas configuré mes dates de début de contrat, du coup j'ai plein de ligne à 0 dans le cache.
![image](https://user-images.githubusercontent.com/6410144/210050020-d260dc0b-0f31-47b7-84a9-ef281f15058d.png)

Absolument rien de grave car je peux clearer toutes les données et recommencer, mais ca éviterai de relancer des appels pour rien ;-)

Bref si tu detectes un changement de date de debut de contrat ou si l'information est dans les données de contrat que tu récupères, tu pourrais cleaner automatiquement ou proposer un bouton, ou ne rien faire et clore cette demande car du travail pour pas grand chose ;-)

**Comment by m4dm4rtig4n** [comment]
Tu as déjà un bouton pour vider le cache du point de livraison :
![image](https://user-images.githubusercontent.com/7872518/210052481-6eb1ab4b-6e5d-4f10-9b75-b07f570defea.png)

Celui d'a coté vide le cache de la passerelle.

**Comment by ioull** [comment]
Oui oui j'avais bien vu mais c'était pour éviter de redemander toutes les infos et purger que celles qui me servaient à rien ;-) 
C'est pour ca que ce n'est pas essentiel ;-) juste pour limiter le nombre d'appel à la passerelle ;-)

**Comment by m4dm4rtig4n** [comment]
Ca va ajouter encore plus de compléxité pour l'utilisateur, on va éviter.
Je verrais pour potentiellement ajouter ce genre de feature le jours où je remarque une saturation sur la passerelle.
