### ISSUE TITLE
[BUG] -  Erreur d'import depuis le passage vers la 0.8.12b1

### ISSUE THREAD

**Issue by gael1980** [m4dm4rtig4n/myelectricaldata#255]
**Description du bug**
Bonjour, depuis la migration du module de la 0.8.11b6 vers la 0.8.12b1 j'ai des erreurs d'import vers MQTT.
Je n'avais aucun problèmes avec la version précédente.

Traceback (most recent call last):
  File "/app/models/jobs.py", line 126, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").daily_annual(
  File "/app/models/export_mqtt.py", line 146, in daily_annual
    get_daily_month = self.stat.get_month(year=year, month=month,
  File "/app/models/stat.py", line 412, in get_month
    begin = datetime.combine(self.now_date.replace(year=year).replace(month=month).replace(day=1), datetime.min.time())
ValueError: day is out of range for month
2022-12-31 11:54:55.871 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2022-12-31 11:54:55.871 -    ERROR : 
2022-12-31 11:54:55.871 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2022-12-31 11:54:55.872 -    ERROR :  day is out of range for month
2022-12-31 11:54:55.872 -    ERROR : 
2022-12-31 11:54:55.872 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2022-12-31 11:54:55.872 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-31 11:54:55.873 -     INFO :  EXPORTATION HOME ASSISTANT
2022-12-31 11:54:55.873 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-31 11:54:55.899 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-31 11:54:55.899 -     INFO :  [02541244566121] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2022-12-31 11:54:55.899 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-31 11:54:55.934 -     INFO :  current_week
2022-12-31 11:54:55.944 -     INFO :   => 361048
2022-12-31 11:54:55.945 -     INFO :  last_week
2022-12-31 11:54:55.954 -     INFO :   => 396753
2022-12-31 11:54:55.954 -     INFO :  current_week_last_year
2022-12-31 11:54:55.963 -     INFO :   => 386910
2022-12-31 11:54:55.964 -     INFO :  last_month
2022-12-31 11:54:55.974 -     INFO :   => 1323916
2022-12-31 11:54:55.974 -     INFO :  current_month
2022-12-31 11:54:55.984 -     INFO :   => 2217119
2022-12-31 11:54:55.985 -     INFO :  current_month_last_year
2022-12-31 11:54:55.996 -     INFO :   => 2323885
2022-12-31 11:54:55.996 -     INFO :  last_month_last_year
2022-12-31 11:54:56.006 -     INFO :   => 1867961
2022-12-31 11:54:56.007 -     INFO :  current_year
2022-12-31 11:54:56.029 -     INFO :   => 15083234
2022-12-31 11:54:56.030 -     INFO :  current_year_last_year
2022-12-31 11:54:56.047 -     INFO :   => 6204616
2022-12-31 11:54:56.047 -     INFO :  last_year
2022-12-31 11:54:56.063 -     INFO :   => 6247741
2022-12-31 11:54:56.064 -     INFO :  yesterday_hp / yesterday_hc
2022-12-31 11:54:56.083 -     INFO :   => HC : 0
2022-12-31 11:54:56.083 -     INFO :   => HP : 0
2022-12-31 11:54:56.084 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2022-12-31 11:54:57.225 -     INFO :   => -7.125456014494532
2022-12-31 11:54:57.226 -     INFO :  current_week_evolution
2022-12-31 11:54:57.226 -     INFO :   => -8.999301832626344
2022-12-31 11:54:57.226 -     INFO :  current_month_evolution
2022-12-31 11:54:57.227 -     INFO :   => -4.594289304333046
2022-12-31 11:54:57.228 -     INFO :  yesterday_evolution
2022-12-31 11:54:57.228 -     INFO :  yesterday
2022-12-31 11:54:57.237 -     INFO :   => 0
2022-12-31 11:54:57.237 -     INFO :  yesterday_1
2022-12-31 11:54:57.246 -     INFO :   => 61492
2022-12-31 11:54:57.247 -     INFO :   => -100.0
2022-12-31 11:54:57.247 -     INFO :  monthly_evolution
2022-12-31 11:54:57.247 -     INFO :  last_month
2022-12-31 11:54:57.258 -     INFO :   => 2647832
2022-12-31 11:54:57.258 -     INFO :  last_month_last_year
2022-12-31 11:54:57.268 -     INFO :   => 3735922
2022-12-31 11:54:57.268 -     INFO :   => -29.125072739741356
{'config': '{"name": "myelectricaldata_history_xxx", "uniq_id": "myelectricaldata_history.xxx", "stat_t": "homeassistant/sensor/myelectricaldata_history/xxx/state", "json_attr_t": "homeassistant/sensor/myelectricaldata_history/xxx/attributes", "unit_of_measurement": "kWh", "device": {"identifiers": ["linky_history_xxx"], "name": "Linky xxx", "model": "Linky", "manufacturer": "MyElectricalData"}}', 'state': '{"state": 61.49}', 'attributes': '{"numPDL": "xxx", "activationDate": "2021-08-03 00:00:00", "lastUpdate": "2022-12-31 11:54:58", "timeLastCall": "2022-12-31 11:54:58", "yesterdayDate": "2022-12-30"}'}
2022-12-31 11:54:58.659 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-31 11:54:58.659 -     INFO :  EXPORT TERMINÉ

**Configuration**
cycle: 14400
debug: false
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: MyElectrical/autogen
  enable: true
  hostname: xxx
  method: synchronous
  org: '-'
  port: 8086
  token: xxx:xxxx
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 192.168.xxx.xxx
  password: xxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: xxx
myelectricaldata:
  'xxx':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: '0.168'
    consumption_price_hc: '0.1263'
    consumption_price_hp: '0.1678'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 2H06-8H06;15H06-17H06
    offpeak_hours_1: 2H06-8H06;15H06-17H06
    offpeak_hours_2: 2H06-8H06;15H06-17H06
    offpeak_hours_3: 2H06-8H06;15H06-17H06
    offpeak_hours_4: 2H06-8H06;15H06-17H06
    offpeak_hours_5: 2H06-8H06;15H06-17H06
    offpeak_hours_6: 2H06-8H06;15H06-17H06
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: xxx

**Type d'installation**
Home assistant OS à jour.
Installation du greffon depuis les modules complementaires de hass

**Version : 0.8.12b1**

**Comment by m4dm4rtig4n** [comment]
A tester, c'est fix dans la 0.8.12-beta2 normalement qui pop dans quelques minutes.

**Comment by gael1980** [comment]
OK, merci.
Je te tiens au courant dès que l'addon sera mis à jour dans hass.

**Comment by m4dm4rtig4n** [comment]
Verdict ?

**Comment by gael1980** [comment]
Bonjour,
Je suis toujours en 0.8.12b1 dans home assistant.
J'attends la mise à jour.

Je te tiens au courant.

Merci

Gaël


Le mar. 3 janv. 2023 à 13:10, m4dm4rtig4n ***@***.***> a
écrit :

**Comment by gael1980** [comment]
Bonjour,
Je suis passé en 0.8.13 dans home assistant. 
Plus de problème mqtt.
Par contre j'ai des valeurs à 0 maintenant.
Encore merci pour ton aide et cette intégration.

 => Finish
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.571 -     INFO :  Génération des données de puissance max journalières.
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.644 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.645 -     INFO :  EXPORT TERMINÉ
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.645 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.645 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.645 -     INFO :  EXPORTATION HOME ASSISTANT
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.646 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.667 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.668 -     INFO :  [02541244566121] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.668 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.715 -     INFO :  current_week
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.726 -     INFO :   => 338362
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.727 -     INFO :  last_week
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.737 -     INFO :   => 423272
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.738 -     INFO :  current_week_last_year
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.748 -     INFO :   => 437633
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.749 -     INFO :  last_month
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.760 -     INFO :   => 2320936
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.760 -     INFO :  current_month
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.770 -     INFO :   => 296769
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.770 -     INFO :  current_month_last_year
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.781 -     INFO :   => 394508
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.782 -     INFO :  last_month_last_year
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.794 -     INFO :   => 2367010
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.795 -     INFO :  current_year
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.805 -     INFO :   => 296769
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.806 -     INFO :  current_year_last_year
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.816 -     INFO :   => 394508
Jan  7 10:59:57 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.817 -     INFO :  last_year
Jan  7 10:59:58 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.864 -     INFO :   => 15187051
Jan  7 10:59:58 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.866 -     INFO :  yesterday_hp / yesterday_hc
Jan  7 10:59:58 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.887 -     INFO :   => HC : 25411.0
Jan  7 10:59:58 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.888 -     INFO :   => HP : 25975.0
Jan  7 10:59:58 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:57.889 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.235 -     INFO :   => -7.548627530963927
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.236 -     INFO :  current_week_evolution
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.236 -     INFO :   => -20.060386701695364
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.236 -     INFO :  current_month_evolution
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.237 -     INFO :   => -24.77490950753851
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.237 -     INFO :  yesterday_evolution
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.237 -     INFO :  yesterday
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.245 -     INFO :   => 51386
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.246 -     INFO :  yesterday_1
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.255 -     INFO :   => 47547
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.255 -     INFO :   => 8.07411613771636
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.255 -     INFO :  monthly_evolution
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.255 -     INFO :  last_month
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.265 -     INFO :   => 4641872
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.266 -     INFO :  last_month_last_year
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.276 -     INFO :   => 4734020
Jan  7 10:59:59 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 10:59:59.276 -     INFO :   => -1.9465063518954224
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.859 -     INFO :  current_week
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.871 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.872 -     INFO :  last_week
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.881 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.882 -     INFO :  current_week_last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.892 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.892 -     INFO :  last_month
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.906 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.906 -     INFO :  current_month
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.918 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.919 -     INFO :  current_month_last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.928 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.928 -     INFO :  last_month_last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.939 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.939 -     INFO :  current_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.948 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.949 -     INFO :  current_year_last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.958 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.958 -     INFO :  last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.966 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.967 -     INFO :  yesterday_hp / yesterday_hc
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.978 -     INFO :   => HC : 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.978 -     INFO :   => HP : 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.978 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.988 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.988 -     INFO :  current_week_evolution
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.988 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.989 -     INFO :  current_month_evolution
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.989 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.989 -     INFO :  yesterday_evolution
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.989 -     INFO :  yesterday
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.997 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:00.997 -     INFO :  yesterday_1
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.005 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.006 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.006 -     INFO :  monthly_evolution
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.006 -     INFO :  last_month
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.014 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.014 -     INFO :  last_month_last_year
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.022 -     INFO :   => 0
Jan  7 11:00:01 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.022 -     INFO :   => 0
Jan  7 11:00:02 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.788 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Jan  7 11:00:02 homeassistant addon_db21ed7f_enedisgateway2mqtt[481138] 2023-01-07 11:00:01.789 -     INFO :  EXPORT TERMINÉ

**Comment by m4dm4rtig4n** [comment]
Les valeurs à 0, sont des valeurs comparative à l'année dernière.
Est-ce que tu as de la donnée sur ses même dates en 2022 ?

**Comment by m4dm4rtig4n** [comment]
Tu as encore le soucis ? Si c'est le cas envoie moi directement un mail avec ton token + pdl stp
Que je puissent tester avec tes données car la je ne sais te répondre :/
> m4dm4rtig4n@gmail.com

**Comment by gael1980** [comment]
J'ai toujours le problème de valeur à 0.

exemple aujourd'hui : 
INFO :   => HC : 0
INFO :   => HP : 0
peak_offpeak_percent_hp VS peak_offpeak_percent_hc
NFO :   => 0
INFO :  current_week_evolution
INFO :   => 0
NFO :  current_month_evolution
NFO :   => 0
NFO :  yesterday_evolution
INFO :  yesterday
INFO :   => 0
NFO :  yesterday_1
INFO :   => 0
INFO :   => 0
INFO :  monthly_evolution
INFO :  last_month
INFO :   => 0
NFO :  last_month_last_year
INFO :   => 0
INFO :   => 0

Lorsque l'on regarde sur les forums, je vois d'autres personnes qui ont un NAN qui s'affiche dans les différentes comparaisons de la carte linky.

Gaël

**Comment by m4dm4rtig4n** [comment]
Je viens de faire un test avec ton PDL + token sur la 0.8.13 et pas de soucis détecté.

**Comment by gael1980** [comment]
Le passage en 0.8.13b5 n'a rien changé.
Est-ce que je tente de supprimer le fichier cache.db afin de refaire une synchro complète ?

**Comment by gael1980** [comment]
Plus de PB.
Merci
