### ISSUE TITLE
[BUG] - Site web interne: les valeurs doivent être des Wh et kWh

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/myelectricaldata#257]
Dans le site web interne accessible sur le port 5000, les valeurs sont présentées comme des W et kW alors que ce sont des Wh et kWh.

**Comment by m4dm4rtig4n** [comment]
D'après Enedis ce sont des W, en tous c'est l'unité qu'il renvoie via leur API.

![image](https://user-images.githubusercontent.com/7872518/210352067-20ff16d7-bac7-41c6-a742-f2492a4c970d.png)

**Comment by pbranly** [comment]
Négatif : les données journalières sont en kWh. 
les données horaires sont en kW

voila ce qui y est écrit sur leur page:

La consommation affichée en "heures" vous permet de voir la puissance moyenne appelée dans la journée, sur le pas de temps affiché (pas horaire 60 minutes ou plus finement selon modalités techniques 30, 15 ou 10 minutes). Elle est exprimée en kW.

La consommation affichée en "jours" est calculée par différence d'index quotidien relevé toutes les 24h et exprimée en kWh.

ce sont des électriciens quand même !
Phil

**Comment by m4dm4rtig4n** [comment]
Fix dans la 0.8.12.

**Comment by pbranly** [comment]
Non corrigé . Please reopen 
Phil

**Comment by m4dm4rtig4n** [comment]
2s papy ca arrive :D
