### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/myelectricaldata#264]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Erreur de calcul du prix de production.
A priori il utilise le prix consumption_price_base (je l'ai fixé à 1 exprès) au lieu du production_price
![image](https://user-images.githubusercontent.com/6410144/210970804-b42e1e09-20cc-4d88-9528-8a418d097753.png)

**Configuration**
  XXXXXXXXXXXXXXXXXXXXX:
    enable: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
    name: "Production"
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_price_base: '1'
    consumption_price_hc: '2'
    consumption_price_hp: '3'
    consumption_max_power: 'false'
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_price: '0.60275'
    production_max_date: "2022-08-18"
    production_detail_max_date: "2022-08-18"
    production_max_power: 'false'
    refresh_addresse: 'false'
    refresh_contract: 'false'

**Type d'installation**
Docker

**Version : 0.8.13-beta1**

**Comment by vingerha** [comment]
C'est la carte Linky de Saniho, non?
Si oui ...il faut ouvrir un issue la bas, pas dans med.

**Comment by m4dm4rtig4n** [comment]
C'est fix est sera en ligne avec la 0.8.13.

**Comment by m4dm4rtig4n** [comment]
@ioull si tu peut tester la 0.8.13-beta2 à l'occasion.
Ca devrait fix ton soucis.

**Comment by ioull** [comment]
Fixé dans la  0.8.13-beta2 ! MERCI !!!
