### ISSUE TITLE
[BUG] - import puissance max

### ISSUE THREAD

**Issue by dudu7731** [m4dm4rtig4n/myelectricaldata#266]
**Description du bug**
Bonjour j'ai une erreur d'import de la puissance maximale suite à la mise a jour d'aujourd'hui : 
2023-01-07 21:59:18.451 -    ERROR : Exception on /usage_point_id/XXXXXXXXXXXX/consumption_max_power/import/2023-01-04 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/main.py", line 232, in fetch_data
    return Ajax(usage_point_id).fetch(target, date)
  File "/app/models/ajax.py", line 145, in fetch
    result["consumption_max_power"] = Power(
  File "/app/models/query_power.py", line 179, in fetch
    target_date = datetime.strptime(item['date'], self.date_format_detail).strftime(self.date_format)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-01-03' does not match format '%Y-%m-%d %H:%M:%S'

**Configuration**
cycle: 14400
debug: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: myelectricaldata
  enable: true
  hostname: X.X.X.X
  method: synchronous
  org: '-'
  port: 8086
  token: XXXXX:XXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: X.X.X.X
  password: XXXXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: XXXX
myelectricaldata:
  'XXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.174'
    consumption_price_hc: '0.133'
    consumption_price_hp: '0.1936'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h30-06h30
    offpeak_hours_1: 22h30-06h30
    offpeak_hours_2: 22h30-06h30
    offpeak_hours_3: 22h30-06h30
    offpeak_hours_4: 22h30-06h30
    offpeak_hours_5: 22h30-06h30
    offpeak_hours_6: 22h30-06h30
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXXX

**Type d'installation**
HassIO 

**Version : X.X.X**

**Comment by dudu7731** [comment]
j'ai oublié la version : 0.8.13-beta1

**Comment by vingerha** [comment]
J'ai aussi HAOS avec 8.13-b1 ... chez moi sans soucis.

**Comment by dudu7731** [comment]
le problème devait être ponctuel car j'ai retenté aujourd'hui et l'import pour cette date est passé.

en tout cas super boulot, c'est extra comme mod !
