### ISSUE TITLE
[BUG] - pas de données de la veille

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#271]
**Description du bug**
Voici l'état de mon sensor (je suis en HP/HC):

Édit: La date de maj est au 07/01 alors qu'il y a tourné le 12/01

```

activationDate: '2021-07-03 00:00:00'
lastUpdate: '2023-01-07 05:07:49'
timeLastCall: '2023-01-07 05:07:49'
yesterdayDate: '2023-01-06'
yesterday: 0
yesterdayLastYearDate: '2022-01-07'
yesterdayLastYear: 0
daily:
  - 0
  - 23.28
  - 31.24
  - 32.12
  - 16.64
  - 19.93
  - 16.27
current_week: 139.51
last_week: 183.37
day_1: 0
day_2: 23.28
day_3: 31.24
day_4: 32.12
day_5: 16.64
day_6: 19.93
day_7: 16.27
```

Néanmoins les données ne remontent pas dans la carte "custom:content-card-linky", nous sommes mardi et la carte affiche la veille comme vendredi:
<img width="454" alt="Capture d’écran 2023-01-10 à 16 59 37" src="https://user-images.githubusercontent.com/72973078/211600456-abbef2a0-fd5e-4842-9f3b-ef3aa2357bb3.png">

**Type d'installation**
HassIO

**Version : 0.8.13-beta1 *

**Comment by buddy31130** [comment]
tu as quoi sur ton interface sur le port 5000 ?

**Comment by buddy31130** [comment]
@floow77 
Cela semble être le même comportement que j'avais sur la version précédente

**Comment by TeddyLafrite** [comment]
Hello
Même problème pour moi sur 2 installations

**Comment by TeddyLafrite** [comment]
activationDate: 2020-06-13 00:00:00
lastUpdate: 2023-01-15 17:31:49
timeLastCall: 2023-01-15 17:31:49
yesterdayDate: 2023-01-14
yesterday: 0
ServiceEnedis: myElectricalData
yesterdayLastYearDate: 2022-01-15
yesterdayLastYear: 0
daily: 0, 1.88, 2.02, 8.32, 7.86, 8.12, 7.63
current_week: 35.87
last_week: 58.46
day_1: 0
day_2: 1.88
day_3: 2.02
day_4: 8.32
day_5: 7.86
day_6: 8.12
day_7: 7.63
current_week_last_year: 118.01
last_month: 477.91
current_month: 94.33
current_month_last_year: 195.5
last_month_last_year: 440.86
last_year: 3209.71
current_year: 94.33
current_year_last_year: 195.5
dailyweek: 2023-01-14, 2023-01-13, 2023-01-12, 2023-01-11, 2023-01-10, 2023-01-09, 2023-01-08
dailyweek_cost: 0, 0.3, 0.3, 1.4, 1.3, 1.3, 1.3
dailyweek_costHP: 0, 0, 0, 0, 0, 0, 0
dailyweek_HP: 0, 1.88, 2.02, 8.32, 7.86, 8.12, 7.63
daily_cost: 0
yesterday_HP_cost: 0
yesterday_HP: 0
day_1_HP: 0
day_2_HP: 1885
day_3_HP: 2029
day_4_HP: 8327
day_5_HP: 7867
day_6_HP: 8127
day_7_HP: 7637
dailyweek_costHC: 0, 0, 0, 0, 0, 0, 0
dailyweek_HC: 0, 0, 0, 0, 0, 0, 0
yesterday_HC_cost: 0
yesterday_HC: 0
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0
peak_offpeak_percent: 0
YesterdayConsumptionMaxPower: 2266
monthly_evolution: 8.4
current_week_evolution: -38.64
current_month_evolution: -51.75
yesterday_evolution: -100
friendly_name: myelectricaldata_consumption_22401XXXX
errorLastCall: 
errorLastCallInterne: 
current_week_number: 02
offpeak_hours_enedis: Lundi ();Mardi ();Mercredi ();Jeudi ();Vendredi ();Samedi ();Dimanche ();
offpeak_hours: 
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''

subscribed_power: 6 kVA
unit_of_measurement: kWh

**Comment by m4dm4rtig4n** [comment]
Il y a déjà une issue à ce sujet.
https://github.com/m4dm4rtig4n/myelectricaldata/issues/249
