### ISSUE TITLE
Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement

### ISSUE THREAD

**Issue by cob94440** [m4dm4rtig4n/myelectricaldata#276]
Bonjour.

Je suis sur la dernière version de l'addon.
J'ai refait les consentements de mes deux points de livraison. (un pour la production un pour la conso).
Sur la conso pas de souci.
En revanche pour la production il me dit que le point de livraison ne correspond pas au token.
J'ai fait une seule demande. Dois je les séparer?

**Comment by cob94440** [comment]
`cycle: 14400
debug: true
home_assistant:
  card_myenedis: true
  enable: true
  discovery_prefix: homeassistant
influxdb:
  bucket: myelectricaldata
  enable: false
  host: influxdb
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: mqtt
  password: mqtt
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "12462373340635":
    enable: 'true'
    token: "secret"
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1841'
    consumption_price_hc: '0.1499'
    consumption_price_hp: '0.2103'
    consumption_max_date: "2021-02-28"
    consumption_detail_max_date: "2021-02-28"
    offpeak_hours_0: 3H00-8H00;12H30-15H30
    offpeak_hours_1: 3H00-8H00;12H30-15H30
    offpeak_hours_2: 0H00-0H00
    offpeak_hours_3: 3H00-8H00;12H30-15H30
    offpeak_hours_4: 3H00-8H00;12H30-15H30
    offpeak_hours_5: 0H00-0H00
    offpeak_hours_6: 0H00-0H00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'true'
    refresh_contract: 'true'
  "12478726430943":
    enable: 'true'
    token: "secret"
    name: "Toit"
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_price_base: '0.1841'
    consumption_price_hc: '0.1499'
    consumption_price_hp: '0.2103'
    consumption_max_date: "2020-08-01"
    consumption_detail_max_date: "2020-08-01"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_price: '0.10'
    production_max_date: "2020-08-01"
    production_detail_max_date: "2020-08-01"
    refresh_addresse: 'true'
    refresh_contract: 'true'`

Voilà mon fichier config. j'ai fait le consentement pour les deux pdl en même temps donc même secret. Essayé avec et sans les "" sur les secrets.
Pour les pdl j'avais deja les "".

**Comment by m4dm4rtig4n** [comment]
Met 3 quote plutot que 1 sinon c'est ilisible :)

**Comment by m4dm4rtig4n** [comment]
Bon ta configuration à l'air bonne, tu est sur de ne pas avoir inverser les token ou autre ?

**Comment by cob94440** [comment]
Non j'ai copié collé de ta passerelle une fois le consentement fait.

Le mer. 18 janv. 2023, 23:57, m4dm4rtig4n ***@***.***> a
écrit :

**Comment by m4dm4rtig4n** [comment]
Si tu sais m'envoyer tes identifier sur mon mail, je peut tester, mais la pour le coup je comprend pas trop d'où vient le soucis :/
J'ai déji eu plusieus utilisateurs avec plusieurs PDL sur le même compte et aucune n'a déjà eu de soucis de ce genre à ma connaissance :/

**Comment by cob94440** [comment]
Je vais t'envoyer les infos. Maintenant en dernière version il s'arrête et me dit :
`2023-01-27 09:29:42.501 -     INFO :  Check config.yaml :
2023-01-27 09:29:42.501 - CRITICAL :  Some mandatory parameters are missing:
2023-01-27 09:29:42.501 - CRITICAL :  - PDL must be 14 characters (pdl => 3)
2023-01-27 09:29:42.501 - CRITICAL :  
2023-01-27 09:29:42.501 - CRITICAL :  You can get list of parameters here :
2023-01-27 09:29:42.501 - CRITICAL :   => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file`

J'ai comparé mon fichier avec le tiens et aucun souci de paramètres manquants

**Comment by m4dm4rtig4n** [comment]
Si tu as ce message d'erreur c'est probablement parce que l'application n'arrive pas à charger ton fichier config.yaml.
Et du coup il charge un fichier par défaut incorrecte.

**Comment by cob94440** [comment]
Effectivement il a recréé un nouveau répertoire et j'ai pas suivi :(

**Comment by cob94440** [comment]
J t'ai envoyé par mail les identifiants

**Comment by cob94440** [comment]
Salut, maintenant que ça semble fonctionner tu pourrais regarder mon souci stp?

**Comment by cob94440** [comment]
Je viens de refaire un consentement juste pour le pdl de production vu que l'autre fonctionne et toujours :
`2023-02-23 20:45:36.368 -    ERROR : 
2023-02-23 20:45:36.368 -    ERROR :  Echec de la récupération des données.
2023-02-23 20:45:36.368 -    ERROR :   => Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement`

**Comment by spamoi33** [comment]
Bonjour,

j'ai le même soucis, mais avec un seul PDL.

Lorsque j'active le mode debug j'ai ce message dans le log : "Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement"

J'ai bien entendu refait le consentement, et modifié la config via l'interface.
Je pense que mon token et mon PDL sont ok puisque j'arrive à avoir les infos correctes via un cURL.

Ai-je loupé un truc ?

Merci !

**Comment by cob94440** [comment]
De mon côté en curl j'ai la même erreur que dans le log.
Ce n'est pas cohérent si en curl pour toi c'est ok et pas dans l'interface

**Comment by spamoi33** [comment]
Bon, et bien j'ai refait un 3ème consentement, reconfiguré mes infos dans l'addon HA, et là j'ai bien des données qui remontent... A suivre !
