### ISSUE TITLE
[FEATURES] - Possibilité de log vers un fichier

### ISSUE THREAD

**Issue by twolaw** [m4dm4rtig4n/myelectricaldata#278]
Utilisant la version `docker-compose`, serait-il possible de donner la possibilité de logger dans un fichier ?

Il log par défaut vers le driver de log de docker, ce qui est bien.
Mais ajouter une option de fichier de log choisi par l'utilisateur serait un plus.

Merci

**Comment by m4dm4rtig4n** [comment]
Pour moi c'est à toi de configurer où tu désire balancer les log du conteneur.
=> https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

**Comment by twolaw** [comment]
Oui mais ça ne me donne pas un fichier de log pérenne dans le temps.
À chaque lancement, j'ai un nouvel id conteneur et donc le chemin vers le log change.

**Comment by twolaw** [comment]
https://github.com/m4dm4rtig4n/myelectricaldata/commit/8fe641dec3e3bcf11bcc021989c7ca0bd640c11f
