### ISSUE TITLE
[FEATURES] - Purge automatique de données plus anciennes que X jours

### ISSUE THREAD

**Issue by Skuair** [m4dm4rtig4n/myelectricaldata#281]
Je ne pense pas que cette fonctionnalité existe déjà, mais dans l'esprit de garder un stockage qui ne grossit pas trop avec le temps (ex: carte SD d'un Pi avec HA), il pourrait être intéressant dans la config de paramétrer plutôt une fenêtre glissante de X jours plutôt qu'une date de début absolue concernant la récupération des données.

Par exemple, dans mon cas, ce qui m'importe c'est de voir la comparaison avec l'année dernière (notamment avec la card de Saniho qui affiche le comparatif à 1 an et 1 mois aant). Je n'ai pas besoin des données de plus de 1 an.
Une config me permettant de mettre une fenêtre de recup de 400 jours par exemple me suffirait. Toute donnée des jours avant ces J-400 seraient automatiquement purgées, et la taille occupée par la DB resterait plutôt stable dans la durée.

**Comment by vingerha** [comment]
J'ai fait une petite analyse et mieux c'est de combiner avec les dates consumption_max_date et consumption_detail_max_date, sinon on charge influx avec des données poiur les purger après
C'est plus facile de specifier #days et ajouter une procedure partial_purge (ce que j'ait fait)
...des idées ?

**Comment by Skuair** [comment]
Je ne suis pas sûr d'avoir bien compris : se baser sur consumption_max_date ? Mais comment rendre cette date glissante automatiquement pour avoir toujours le même intervalle de jours ?

**Comment by vingerha** [comment]
bien compris mais j'ai vu un truc efficace...la recup des données pour une période plus longue qui est chargé =dans Influx...pur être partiellement purgé après. Je pense que t'as raison...l'un n'est pas liée avec l'autre.
Donc ma proposition est:
- ajout d'une paramêtre, p.e. 'keep_influx_days'
- ajout d'un purge pour les données plus ancienne que [aujourd'hui] - [keep_influx_days]
- le purge se fait après les données sont télécharge dans influx...pas efficace mais bon

**Comment by Skuair** [comment]
Pour moi, vous me direz si ça a du sens du point de vue de cette appli, mais Influx ne devrait pas être lié à l'opération de purge et laissé de côté.
En effet, influx est optionnel, et l'utilisateur qui l'a activé a sûrement des données d'autres sources dans son entrepôt. Il peut très bien vouloir conserver un historique beaucoup plus grand dans Influx, tout en préférant avoir sa bdd Myelectricaldata petite. Et j'imagine qu'il existe des solutions standalone pour purger Influx si nécessaire. Ça resterai de la responsabilité du user de gérer son entrepôt influx.

Du coup j'imaginerais plutôt un paramètre appelé "max_retention_days" par exemple qui n'agit que sur la bdd Myelectricaldata et non influx, qui purge comme tu dis selon le calcul today - ce param.
Après c'est peut-être ce que tu dis dans ton dernier point "la purge se fait après les données téléchargées dans Influx".

**Comment by vingerha** [comment]
Tous que j'ai écrit c'est que pour effacer les données MED de la bdd configuré...c'est pas la même que retention et retention est fait par configurer la bdd.

**Comment by m4dm4rtig4n** [comment]
Une purge automatique dans l'influxdb n'est pas forcement pour moi le taff de MED.
InfluxDB le fait déjà de lui même parfaitement.

Pour une durée de retention sur le cache de MED (cache.db) je n'y suis pas forcement favorable car ca risque de généré des demandes inutile sur la passerelle.
Sachant que le cache.db pour 3 ans d'historique ne fait que quelques mo en fin de compte.
Ce n'est pas le cache qui va venir saturer un RPI ou autre (a moins d'avoir 100mo de disque sur celui-ci...)

**Comment by vingerha** [comment]
Donc... de mon avis on peut cloire ce cas. Filtrer des données dans les dash est posisble par Influx/Grafana etc...
