### ISSUE TITLE
[BUG] - retour sur données manquant la veille Daily et Max Power

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/myelectricaldata#289]
Probablement pas liée a la version mais: avec 8.13 et 8.14-beta
La veille ne monte plus chez moi, en mode BASE

- Daily NOK
- Max Power NOK
- Détails OK
- HP OK (et car en BASE, c'est pareille que Daily)

En changeant end_str dans query_daily vers 28 Jan (au lieu de 27 d'origine), Daily est encore recupéré

Je voix la même comportement comme avant pour Daily ... mais différent pour Détails et Max Power

**Comment by vingerha** [comment]
Maj, 

- Situation d'origine: Daily + MaxP NOK
- Situation avec end_str 29Jan (au lieu de 28): NOK
- Situation avec end_str 30 Jan (au lieu de 28): OK
- Détail+HP OK dans les trois situations

**Comment by vingerha** [comment]
Maj
aujourd'hui erreurs n'importe quelle end_str, sur daily et max power
J'assume un soucis avec Enedis
```
Traceback (most recent call last):
  File "/app/models/query_power.py", line 95, in run
    "description": json.loads(data.text)["detail"],
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by m4dm4rtig4n** [comment]
> Maj aujourd'hui erreurs n'importe quelle end_str, sur daily et max power Détails sont bien recupéré J'assume un soucis avec Enedis
> 
> ```
> 2023-01-27 08:18:02.681 -    ERROR : Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/app/models/query_daily.py", line 114, in run
>     "description": json.loads(data.text)["detail"],
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2023-01-27 08:18:02.685 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
> 2023-01-27 08:18:02.685 -    ERROR : 
> 2023-01-27 08:18:02.685 -    ERROR :  Expecting value: line 1 column 1 (char 0)
> 2023-01-27 08:18:02.685 -    ERROR : 
> 2023-01-27 08:18:02.686 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
> 2023-01-27 08:18:02.686 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
> ```

C'était la passerelle qui était dans les choux cette erreur.

**Comment by m4dm4rtig4n** [comment]
J'ai eu un rollback sur la passerelle sur la gestion du cache que j'avais fix il y a quelques jours...
Normalement tt doit être revenu en ordre le daily.
