### ISSUE TITLE
[FEATURES] - Intégrer sensor myelectricaldata dans le dashboard energy

### ISSUE THREAD

**Issue by ZOKOB** [m4dm4rtig4n/myelectricaldata#290]
Bonjour, 

Tout abord félicitation pour tout votre travail ! 
Je voudrais savoir si il serait possible dans une prochaine version d'intégrer myelectricaldata dans le dashboard energy de HA ? 

Bonne journée à vous !

**Comment by vingerha** [comment]
Le senor te donne déjà les infos pour en construire un (p.e.) utility-meter toi même (!). Stp détailler ce que tu pense.

**Comment by ZOKOB** [comment]
Le problème venais du fait que je pouvais pas ajouter le sensor au dashboard energy.
Après longue recherche avec un membre du discord on a trouver il faut créer un fichier customize.yaml:
Et ajouter ceci : 
 sensor.myelectricaldata_consumption_xxxxxxxx 
   state_class: total_increasing
   device_class: energy

J'attends demain pour voir si tout remonte :) 

Bonne soirée

**Comment by vingerha** [comment]
Entretemps j'ai pensé un peu plus mais c'est pas si facile parceque les données ont un retard d'un jour (si le tout marche comme prévu). Donc, avec ci-dessus on va registrer la valeur de hier pour aujourd'hui. C'est pas trops grave mais pas correcte non plus. Sans (!) priotrité je vais voir comment le faire .. pas évident car il faut probablement aller directement dans la bdd et avec ça des soucis en plus puisque ça doit marcher pour sqlite, mariadb..etc.

**Comment by ZOKOB** [comment]
Bonjour, merci de votre réponse, j'ai effectué plusieurs tests dans HA test de conversion de la valeur journalière en heure, mais les résultats ne sont pas bons. aprés avoir regardé sur un groupe Facebook le plugin myenedis qui utilise la gateway myelectricaldata fonctionne correctement dans le dashboard energy.
J'attends que l'API de enedis soit de nouveau UP est je teste :) 

Je vous ferai un retour ici.
Bon dimanche

**Comment by pbranly** [comment]
Bonjour 
Quel est le sensor de myenedis qui fonctionne ? 
phil

**Comment by ZOKOB** [comment]
Bonjour, d'aprés le groupe, c'est le sensor energy_hours

**Comment by pbranly** [comment]
Effectivement il doit fonctionner celui la . 
![68112461-10E1-43C2-B18D-C3B81958B56A](https://user-images.githubusercontent.com/22018509/215322113-a7bfe251-811c-40c2-bbb8-b4a76ee7c443.jpeg)

**Comment by ZOKOB** [comment]
à tester :) ,
Pour le moment, je ne peux pas tester, car l'api V1 d'Enedis est dans les choux
je teste dès que celle-ci revient.

**Comment by vingerha** [comment]
Explique moi, comme tu dit 'correctement' ... monter une valeur dans le dash est qu'une partie...le monter avec lla date correcte c'est différent.  Est-ce que tu dit que to monte le sensor myenedis avec une date de hier ou de ton exemple, de 27/Jan?

**Comment by ZOKOB** [comment]
Je n'ai pas encore tester c'est les gens qui dise ça sur le groupe Facebook.
Il faut tester je sais pas quelle valeurs sa récupère, ce que je sais juste c'est que l'ancienne version de myenedis fonctionner parfaitement dans le dashboard energy elle fonctionner avec l'ancienne gateway enedisgateway.tech.
Donc je pense que celle ci a pas trop changer. 
Je teste ça dès que l'API revient.

**Comment by vingerha** [comment]
Je veux bien te croire que ça monte  (et je l'espère aussi)  mais je doute encore que la comninaison dates + valeurs ne sont pas bon dans le dash

**Comment by ZOKOB** [comment]
J'ai vu ce matin que l'api d'Enedis est de nouveau en ligne, au moment où je vais tester le module myenedis l'api n'est plus disponible.
Du coup erreurs : Error JSON : {"detail":"Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement"}
Data answer: {'detail': 'Le point de livraison ne correspond au token fournis pour le réinitialiser il vous suffit de refaire un consentement'}

Pourtant, mon consentement est fonctionnel avec Myelectricaldata sous docker.

Je ne sais pas ce qu'ils font avec cette API, mais c'est compliqué, j'ai l'impression…

Bonne soirée :)

**Comment by vingerha** [comment]
Je ne sais pas si connu mais les tokens et leur sitde de consentement MyEnedis et MED sont différent.
MyEndis: https://enedisgateway.tech/ ... ce qui va disparaitre dans 2 moi ou apres que https://myelectricaldata.fr/

**Comment by ZOKOB** [comment]
Myenedis intégré la version de Myelectricaldata.
Quand on configure l'intégration il faut choisir entre enedis et myelectricaldata.
Mais tant que l'API est down je pense qu'on ne pourra pas faire l'essai.
Bonne journée.

**Comment by bueno79** [comment]
courage les gars. Avoir la remonte par heure dans le dashboard Energy depuis MyElectricalData, ca serait ENORME !

**Comment by vingerha** [comment]
Je repète que la solution n'est pas possible car les données les plus récents sont de 'hier'. Comment antidater ? Je ne sais aucn solution sauf via la bdd manuellement/SQL

**Comment by m4dm4rtig4n** [comment]
> courage les gars. Avoir la remonte par heure dans le dashboard Energy depuis MyElectricalData, ca serait ENORME !

C'est pas que je ne veut pas c'est que comme le dit @vingerha et comme je le repéte souvent, Home Assistant ne permet d'envoyer des données antidatée.

Des utilisateurs ont essayer d'ajouter ce genre de fonctionnalité manuellement via des insert en Base de données, sauf qu'il y a de gros risque de corrumption de données... (et de planter complétement votre HA)
=> Je ne mettrais donc pas en place ce genre de fonctionnalité :/

Si vous souhaité avoir de beau graphique, le combo Grafana, InfluxDB est la meilleurs solution.

**Comment by bueno79** [comment]
mais l'API myEnedis le fait non ? Et c'est pareil de ce que je comprend.

**Comment by m4dm4rtig4n** [comment]
L'information je l'ai mais c'est home assistant qui ne sais pas les l'intégrer car il fait uniquement du temps réel. 
Tu peut pas lui envoyer une donnée dans le passé.
Et comme la consommation envoyé par enedis est toujours celle de la vielle, je peut rien faire...

**Comment by bueno79** [comment]
yes je comprend bien. et si on mettais une value nulle en day 0 et qu on l'ecrase quand on recoit celle de Enedis ?

**Comment by vingerha** [comment]
Pense bien...quand les données arrives HA les enrégistre avec date 'maintenant' mais leurs date/heure doivent être hier 01:00 ou 01:30 ou 20:00 etc....comment le faire? Il y a 48 valeurs pour 'hier'. Pour cela il faut créer un script qui directemebt rentre dans la bdd. 
Je doute que l'API Enedis le fait correctement, j'aimerai bien la preuve

**Comment by vingerha** [comment]
@m4dm4rtig4n je pense que to peux ferms ce sujet, non?

**Comment by ZOKOB** [comment]
Je pense que c'est bon :) 
Mais si vous avez une idée par la suite je suis preneur 
Bonne soirée

**Comment by bueno79** [comment]
c est a dire ? t as reussi ? Comment t as fait ?
