### ISSUE TITLE
[HELP] - 404 sur les consentements

### ISSUE THREAD

**Issue by montaignec** [m4dm4rtig4n/myelectricaldata#291]
**Description de la fonctionnalité**
sur https://myelectricaldata.fr/  Le lien de demande de consentement renvoie sur une page" erreur 404 La page que vous recherchez n’existe pas.

**Comment by m4dm4rtig4n** [comment]
J'ai crée un ticket chez Enedis à ce sujet.

**Comment by didierhassio** [comment]
Bonjour,
est-ce pour cela que mon log se termine ainsi:
`2023-01-30 13:30:22.983 -     INFO :  DÉMARRAGE DU JOB D'IMPORTATION DANS 10S
2023-01-30 13:30:22.990 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-30 13:30:22.997 -     INFO :   => 10s
2023-01-30 13:30:24.004 -     INFO :   => 9s
2023-01-30 13:30:25.005 -     INFO :   => 8s
2023-01-30 13:30:26.007 -     INFO :   => 7s
2023-01-30 13:30:27.008 -     INFO :   => 6s
2023-01-30 13:30:28.010 -     INFO :   => 5s
2023-01-30 13:30:29.010 -     INFO :   => 4s
2023-01-30 13:30:30.012 -     INFO :   => 3s
2023-01-30 13:30:31.014 -     INFO :   => 2s
2023-01-30 13:30:32.015 -     INFO :   => 1s
2023-01-30 13:30:33.037 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-30 13:30:33.038 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2023-01-30 13:30:33.038 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2023-01-30 13:30:33.039 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2023-01-30 13:30:33.039 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2023-01-30 13:30:33.039 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2023-01-30 13:30:33.040 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2023-01-30 13:30:33.040 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`

**Comment by m4dm4rtig4n** [comment]
@didierhassio avec le formatage c'est mieux ;)

Et non ton soucis n'a rien à voir avec le soucis au dessus, tu est sur quelle version ?
Ton soucis à était fix en 0.8.13 si mes souvenir sont bon.

**Comment by didierhassio** [comment]
En fait, j'avais un souci (log ci-dessous) j'ai donc restauré la version 0.8.13-beta1 et c’est là que j’ai eu le message que j’ai postée précédemment.
En cherchant j’ai vu que la version  0.8.13-8 était à l’origine de l’erreur de PDL, j’ai donc reinstallé la version 0.8.13-8 et copié les fichiers cache.db et config.yaml de l’ancien répertoire vers le nouveau. Maintenant cela à l’air de fonctionner.
Merci pour l'aide,
2023-01-30 10:31:46.044 -     INFO :        refresh_contract: False
2023-01-30 10:31:46.045 -     INFO :        token: ** hidden **
2023-01-30 10:31:46.045 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-30 10:31:46.045 -     INFO :  Check config.yaml :
2023-01-30 10:31:46.045 - CRITICAL :  Some mandatory parameters are missing:
2023-01-30 10:31:46.045 - CRITICAL :  - PDL must be 14 characters (pdl => 3)
2023-01-30 10:31:46.045 - CRITICAL :  
2023-01-30 10:31:46.045 - CRITICAL :  You can get list of parameters here :
2023-01-30 10:31:46.046 - CRITICAL :   => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file

**Comment by ploufe** [comment]
je vois que l'issue est fermée.
Pourtant j'ai également l'"erreur 404 en cherchant a obtenir le consentement ENEDIS (sur chrome & firefox / sur pc & sur mac / sur mon ip perso & au boulot...).
Une methode?

**Comment by julienbdx** [comment]
Pareil, j'ai le même souci. Je suivais la résolution du sujet mais je suis peut être passé à côté de qqch ?

**Comment by m4dm4rtig4n** [comment]
J'ai clos parce que je suis rester sur le message de @didierhassio qui n'avait rien à voir avec le soucis de 404... sorry je réouvre :D

**Comment by m4dm4rtig4n** [comment]
J'ai recu la com officiel d'Enedis au sujet du soucis de 404 sur le consentement, tjr en cours d'investigation chez Enedis :
![image](https://user-images.githubusercontent.com/7872518/215782539-650bd518-be8e-4fb9-aec8-257289827cfe.png)

**Comment by bunz13** [comment]
Bonjour,
c'est toujours en panne chez Enedis ?
car de mon côté j'ai toujours l'erreur 404.

**Comment by GillesMattioli** [comment]
Bonjour,
c'est toujours en panne chez Enedis ?
car de mon côté j'ai toujours l'erreur 404.

**Comment by m4dm4rtig4n** [comment]
Pas de son, pas d'image de leur part :/

**Comment by GillesMattioli** [comment]
en tous cas merci pour ton boulot ! A+

Le ven. 3 févr. 2023 à 17:13, m4dm4rtig4n ***@***.***> a
écrit :

**Comment by oxamafia** [comment]
Bonsoir à tous

même souci de mon côté pour la version classique (hors MQTT)
En tout cas, j’en profite pour te remercier @m4dm4rtig4n pour tout ce que tu mets à notre disposition ! Et même pour le suivi que tu réalises ! C’est vraiment génial :)

**Comment by m4dm4rtig4n** [comment]
Je les ai relancé hier, le sujet est en cours de traitement...

**Comment by hervefox** [comment]
si enedis est aussi rapide pour leur site internet que pour un raccordement , ça promet! 
404 encore ce soir

**Comment by julienbdx** [comment]
Heureusement ils ne gèrent pas les centrales nucléaires !

**Comment by slider07210** [comment]
Bonsoir à tous, 
Pour info je viens à l'instant de faire une demande de consentement qui a fonctionné.
Bonne soirée

**Comment by cherjr** [comment]
Pour moi, la reaction a changé, mais pas de success: 
---
Site fermé temporairement pour maintenance
Nous travaillons actuellement à l'amélioration du site. Nous vous invitons à revenir ultérieurement.

**Comment by hervefox** [comment]
Zut j'ai raté le créneau où c'était ouvert

**Comment by m4dm4rtig4n** [comment]
Perso je viens de réussir à faire un consentement.
On dirait que le service devrait être bientôt de nouveau opérationnel.

**Comment by syl20-30** [comment]
Je vient également de faire une demande de consentement qui à réussi.

J'ai pas de remonter d'info encore et un de mes PDL et en erreur au niveau du sensor. 
Pour Info:
Error setting up entry 245*************** for myEnedis
07:15:21 – (ERREUR) MyEnedis (intégration personnalisée)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myEnedis/__init__.py", line 120, in async_setup_entry
    await coordinator_enedis.async_setup()
  File "/config/custom_components/myEnedis/__init__.py", line 344, in async_setup
    await self.hass.async_add_executor_job(self.update_OptionsMyEnedis)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/myEnedis/__init__.py", line 254, in update_OptionsMyEnedis
    hpcost = float(self.entry.options.get(HP_COST, "0.0"))
ValueError: could not convert string to float: '0,1705'

**Comment by m4dm4rtig4n** [comment]
> Je vient également de faire une demande de consentement qui à réussi.
> 
> J'ai pas de remonter d'info encore et un de mes PDL et en erreur au niveau du sensor. Pour Info: Error setting up entry 245*************** for myEnedis 07:15:21 – (ERREUR) MyEnedis (intégration personnalisée)
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/myEnedis/**init**.py", line 120, in async_setup_entry await coordinator_enedis.async_setup() File "/config/custom_components/myEnedis/**init**.py", line 344, in async_setup await self.hass.async_add_executor_job(self.update_OptionsMyEnedis) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/myEnedis/**init**.py", line 254, in update_OptionsMyEnedis hpcost = float(self.entry.options.get(HP_COST, "0.0")) ValueError: could not convert string to float: '0.1705'

C'est un erreur de l'intégration MyEnedis, pas de MED :)
Sinon regarde juste le champ price que tu as probablement set avec un string à la place d'un float (pas de , ou espace)

**Comment by cherjr** [comment]
J'ai réussi! Merci, m4dm4rtig4n

**Comment by peluho** [comment]
Bonjour,

la demande fonctionne très bien, maintenant. Par contre, tout les sensors son indisponible. J'ai aucun idée pourquoi.

![image](https://user-images.githubusercontent.com/38323825/220298386-e1a3d60d-82e3-48b8-8c77-25578e34e8b0.png)

![image](https://user-images.githubusercontent.com/38323825/220296681-a12cec03-7f3f-491d-b7f3-09ae25e89872.png)

**Comment by hervefox** [comment]
bonjour,
Je découvre le service, 
j'ai enfin réussi le consentement,
Me reste à passer à l'intégration , vous avez un tutoriel à jour à me proposer ?

**Comment by m4dm4rtig4n** [comment]
> Bonjour,
> 
> la demande fonctionne très bien, maintenant. Par contre, tout les sensors son indisponible. J'ai aucun idée pourquoi.
> 
> ![image](https://user-images.githubusercontent.com/38323825/220298386-e1a3d60d-82e3-48b8-8c77-25578e34e8b0.png)
> 
> ![image](https://user-images.githubusercontent.com/38323825/220296681-a12cec03-7f3f-491d-b7f3-09ae25e89872.png)

C'est MyEnedis est pas MED, go sur le github de Saniho qui gérée l'intégration :)
https://github.com/saniho/apiEnedis

> bonjour, Je découvre le service, j'ai enfin réussi le consentement, Me reste à passer à l'intégration , vous avez un tutoriel à jour à me proposer ?
Si as de la doc dans le wiki si besoin :
https://github.com/m4dm4rtig4n/myelectricaldata/wiki/01.-Home

**Comment by syl20-30** [comment]
> > Je vient également de faire une demande de consentement qui à réussi.
> > J'ai pas de remonter d'info encore et un de mes PDL et en erreur au niveau du sensor. Pour Info: Error setting up entry 245*************** for myEnedis 07:15:21 – (ERREUR) MyEnedis (intégration personnalisée)
> > Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/myEnedis/**init**.py", line 120, in async_setup_entry await coordinator_enedis.async_setup() File "/config/custom_components/myEnedis/**init**.py", line 344, in async_setup await self.hass.async_add_executor_job(self.update_OptionsMyEnedis) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/myEnedis/**init**.py", line 254, in update_OptionsMyEnedis hpcost = float(self.entry.options.get(HP_COST, "0.0")) ValueError: could not convert string to float: '0.1705'
> 
> C'est un erreur de l'intégration MyEnedis, pas de MED :) Sinon regarde juste le champ price que tu as probablement set avec un string à la place d'un float (pas de , ou espace)

Exact !!! désolé mais j'ai un espace qui s'est glissé !!

Par contre, je pense que l'API n'est pas encore opérationnel sur le consentement car j'ai un retour 403:
{"detail":"Not authenticated"}

De ton avis, c'est normal ?

**Comment by m4dm4rtig4n** [comment]
> > > Je vient également de faire une demande de consentement qui à réussi.
> > > J'ai pas de remonter d'info encore et un de mes PDL et en erreur au niveau du sensor. Pour Info: Error setting up entry 245*************** for myEnedis 07:15:21 – (ERREUR) MyEnedis (intégration personnalisée)
> > > Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/myEnedis/**init**.py", line 120, in async_setup_entry await coordinator_enedis.async_setup() File "/config/custom_components/myEnedis/**init**.py", line 344, in async_setup await self.hass.async_add_executor_job(self.update_OptionsMyEnedis) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/myEnedis/**init**.py", line 254, in update_OptionsMyEnedis hpcost = float(self.entry.options.get(HP_COST, "0.0")) ValueError: could not convert string to float: '0.1705'
> > 
> > 
> > C'est un erreur de l'intégration MyEnedis, pas de MED :) Sinon regarde juste le champ price que tu as probablement set avec un string à la place d'un float (pas de , ou espace)
> 
> Exact !!! désolé mais j'ai un espace qui s'est glissé !!
> 
> Par contre, je pense que l'API n'est pas encore opérationnel sur le consentement car j'ai un retour 403: {"detail":"Not authenticated"}
> 
> De ton avis, c'est normal ?

Je suis pas le dev de MyEnedis, ici c'est MyElectricalData (MED).
Si tu as besoin d'aide sur MyEnedis => https://github.com/saniho/apiEnedis

**Comment by m4dm4rtig4n** [comment]
Comme les consentements refonctionne je clos le ticket.
