### ISSUE TITLE
[BUG] - cannot touch cache.db

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/myelectricaldata#293]
**Description du bug**
L'application ne se lance plus:

[06:39:56] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
touch: cannot touch '/config/myelectricaldata/cache.db': No such file or directory
/etc/cont-init.d/99-run.sh: exiting 1

![image](https://user-images.githubusercontent.com/72973078/215400156-d0a7ae8d-a24b-48dd-a7dc-5e2a885fd175.jpeg)

**Configuration**
Addon sur HassIO

**Version : 0.8.13-8**

**Comment by m4dm4rtig4n** [comment]
C'est liée à l'addon pour le coup, go crée une issue plutôt sur le github d'@alexbelgium et tag moi si besoin.

**Comment by alexbelgium** [comment]
Bonjour, pourrais-tu en profiter pour rajouter le log complet (avec les lignes précédentes) et les options de l'addon ? merci d'avance
