### ISSUE TITLE
[BUG] - petite typo sur la page myelectrical data

### ISSUE THREAD

**Issue by dudu7731** [m4dm4rtig4n/myelectricaldata#299]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
il y a une typo sur la page myelectricaldata 
"Enedis met à disposition les données en J+1 à partir de 0h UTC minUmun "

**Configuration**
N/A

**Type d'installation**
N/A

**Version : 8.1.13**

**Comment by m4dm4rtig4n** [comment]
Fix dans la futur 0.8.14
