### ISSUE TITLE
[FEATURES] - 

### ISSUE THREAD

**Issue by Alindil** [m4dm4rtig4n/myelectricaldata#304]
Bonjour,

je voudrais faire un graph dans home assistant via MQTT pour comparer la consommation de l'année en cours par mois avec la consommation de l'année précédente par mois.

Donc est-ce qu'il serait possible d'avoir les consommations par mois de l'année en cours et de l'année n-1 dans les sensors.

Merci

**Comment by dudu7731** [comment]
ce n'est pas déjà présent ? 
![image](https://user-images.githubusercontent.com/117290248/221793049-f0f0d2ec-c39a-4da6-9933-df7ef58bdd40.png)

**Comment by Alindil** [comment]
Ah j'ai pas été assez précis. Je rectifie mon poste d'origine

**Comment by m4dm4rtig4n** [comment]
Normalement tu as déjà tt les information nécéssaire dans MQTT, exemple :
![image](https://user-images.githubusercontent.com/7872518/221841792-7beac829-0355-42a4-b23e-984e93b4f4ed.png)

**Comment by Alindil** [comment]
Je n'ai pas de topic consumption
![image](https://user-images.githubusercontent.com/30829631/221854977-1a362674-14c7-4279-bbf5-d9db3d228ef2.png)

Peut être que mon paramétrage n'est pas correct
![image](https://user-images.githubusercontent.com/30829631/221855621-a1407fc8-2d6c-46e6-93af-db030d66130e.png)

**Comment by Alindil** [comment]
Bon je viens de regarder ce matin et du coup j'ai bien maintenant consumption qui est présent.
Merci
