### ISSUE TITLE
[FEATURES] - Compatibilité Energy dashboard

### ISSUE THREAD

**Issue by flouck** [m4dm4rtig4n/myelectricaldata#306]
Est-il envisagé de rendre compatible le sensor avec le dashboard Energy de Home Assistant ?
L ancienne intégration de saniho https://github.com/saniho/apiEnedis fonctionnait bien avec l'Energy dashboard, si ça peut aider.

**Comment by m4dm4rtig4n** [comment]
Hello, 

On as déjà parler pas mal de fois et non je rendrais pas compatible le sensor avec la dashboard energy car HA ne permet pas d'enregistrer de la donnée dans le passé.

L'intégration de Saniho gérée cette fonctionnalité grâce à une bidouille et avec un delta d'1j dans les graph.
Il me semble que d'autre utilisateurs ont réussi à reproduire cette manip directement dans HA via de simple scénario.
