### ISSUE TITLE
[BUG] - Erreur lors de l'exportation des données dans MQTT - day is out of range for month

### ISSUE THREAD

**Issue by alainvdu69** [m4dm4rtig4n/myelectricaldata#316]
**Description du bug**
Bonjour,
Suite au souci sur le DNS, j'ai été obligé de relancer l'ADDON (le 2 avril).
Et une nouvelle erreur apparait. Au moins sur un des 2 PDL déclarés.

2023-04-02 15:24:01.004 -     INFO :  Génération des données annuelles
Traceback (most recent call last):
  File "/app/models/jobs.py", line 126, in job_import_data
    ExportMqtt(self.usage_point_id, "consumption").daily_annual(
  File "/app/models/export_mqtt.py", line 107, in daily_annual
    get_daily_year = self.stat.get_year(year=year)
  File "/app/models/stat.py", line 415, in get_year
    end = datetime.combine(self.now_date.replace(year=year).replace(day=last_day_of_month).replace(month=12),
ValueError: day is out of range for month
2023-04-02 15:24:01.093 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-04-02 15:24:01.093 -    ERROR : 
2023-04-02 15:24:01.094 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2023-04-02 15:24:01.094 -    ERROR :  day is out of range for month
2023-04-02 15:24:01.094 -    ERROR : 
2023-04-02 15:24:01.094 -    ERROR : 

**Configuration**
##########################

CONFIG PDL
##########################
myelectricaldata:

APPART
"191":
token: ""
enable: 'true'
name: "Appart"
addresses: 'true'
cache: 'true'
consumption: 'true'
consumption_detail: 'true'
consumption_price_base: '0.1615'
consumption_price_hc: '0.124364'
consumption_price_hp: '0.2228'
consumption_max_date: ""
consumption_detail_max_date: ""
offpeak_hours_0: 22H00-6H00 # LUNDI
offpeak_hours_1: 22H00-6H00 # MARDI
offpeak_hours_2: 22H00-6H00 # MERCREDI
offpeak_hours_3: 22H00-6H00 # JEUDI
offpeak_hours_4: 22H00-6H00 # VENDREDI
offpeak_hours_5: 22H00-6H00 # SAMEDI
offpeak_hours_6: 22H00-6H00 # DIMANCHE
plan: BASE
production: 'false'
production_detail: 'false'
production_max_date: ""
production_detail_max_date: ""
refresh_addresse: 'false'
refresh_contract: 'false'

STUDIO
"191":
enable: 'true'
token: ""
name: "Studio"
cache: 'true'
consumption: 'true'
consumption_detail: 'true'
consumption_price_base: '0.1615'
consumption_price_hc: '0.124364'
consumption_price_hp: '0.2228'
consumption_max_date: "2021-06-01"
consumption_detail_max_date: "2021-06-01"
offpeak_hours_0: 22H00-6H00 # LUNDI
offpeak_hours_1: 22H00-6H00 # MARDI
offpeak_hours_2: 22H00-6H00 # MERCREDI
offpeak_hours_3: 22H00-6H00 # JEUDI
offpeak_hours_4: 22H00-6H00 # VENDREDI
offpeak_hours_5: 22H00-6H00 # SAMEDI
offpeak_hours_6: 22H00-6H00 # DIMANCHE
plan: BASE
production: 'false'
production_detail: 'false'
production_max_date: ""
production_detail_max_date: ""
refresh_addresse: 'false'
refresh_contract: 'false'

**Type d'installation**
HassIO : addon mis à dispo par Alex

**Version : X.X.X**
Version : Current version: 0.8.13-11

**Comment by m4dm4rtig4n** [comment]
Fix dans le futur 0.8.14.
