### ISSUE TITLE
[HELP] -   error    wrong new line character: expected \n  (new-lines)

### ISSUE THREAD

**Issue by Mrsore** [m4dm4rtig4n/myelectricaldata#318]
**Description de la fonctionnalité**
[22:43:23] FATAL: Config file has an invalid yaml format. Please check the file in /config/myelectricaldata/config.yaml. Errors list above. You can check yaml validity with the online tool yamllint.com
**Type d'installation**
Add-on version: 0.8.13-11
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.0
 Home Assistant Supervisor: 2023.04.0
**Fichier de config :** 
cycle: 14400  # 4H
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  method: synchronous
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: mosquitto
  port: 1883
  username: null
  password: null
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "XXXXX":
    enable: "true"
    token: XXXXXX
    name: Maison
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.145907"
    consumption_price_hc: "0.10240"
    consumption_price_hp: "0.20179"
    consumption_max_date: 2021-06-01
    consumption_detail_max_date: 2021-06-01
    offpeak_hours_0: 23H06-7H06
    offpeak_hours_1: 23H06-7H06
    offpeak_hours_2: 23H06-7H06
    offpeak_hours_3: 23H06-7H06
    offpeak_hours_4: 23H06-7H06
    offpeak_hours_5: 23H06-7H06
    offpeak_hours_6: 23H06-7H06
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: 2021-06-01
    production_detail_max_date: 2021-06-01
    refresh_addresse: "false"
    refresh_contract: "false"

J'ai ce message depuis la dernière mise à jour, sans raison particulière est-ce une erreur de ma part ?
Merci pour votre aide !

**Comment by vingerha** [comment]
On ne peut rien faire avec ce code non-formatté, est ce que t'as utilisé yamllint.com comme proposé avec l'erreur?
Commence avec yamlint 
Si après encore des soucis, ajoute ton fichier et ne pas copier/coller car ça va pas copier 100%

**Comment by m4dm4rtig4n** [comment]
> **Description de la fonctionnalité** [22:43:23] FATAL: Config file has an invalid yaml format. Please check the file in /config/myelectricaldata/config.yaml. Errors list above. You can check yaml validity with the online tool yamllint.com **Type d'installation** Add-on version: 0.8.13-11 You are running the latest version of this add-on. System: Debian GNU/Linux 11 (bullseye) (amd64 / qemux86-64) Home Assistant Core: 2023.4.0 Home Assistant Supervisor: 2023.04.0 **Fichier de config :** cycle: 14400 # 4H debug: true wipe_influxdb: false home_assistant: enable: true discovery: true discovery_prefix: homeassistant influxdb: enable: true hostname: influxdb port: 8086 token: myelectricaldata org: myelectricaldata bucket: myelectricaldata method: synchronous batching_options: batch_size: 1000 flush_interval: 1000 jitter_interval: 0 retry_interval: 5000 max_retry_time: 180_000 max_retries: 5 max_retry_delay: 125_000 exponential_base: 2 mqtt: enable: true hostname: mosquitto port: 1883 username: null password: null prefix: myelectricaldata client_id: myelectricaldata retain: true qos: 0 myelectricaldata: "XXXXX": enable: "true" token: XXXXXX name: Maison addresses: "true" cache: "true" consumption: "true" consumption_detail: "true" consumption_price_base: "0.145907" consumption_price_hc: "0.10240" consumption_price_hp: "0.20179" consumption_max_date: 2021-06-01 consumption_detail_max_date: 2021-06-01 offpeak_hours_0: 23H06-7H06 offpeak_hours_1: 23H06-7H06 offpeak_hours_2: 23H06-7H06 offpeak_hours_3: 23H06-7H06 offpeak_hours_4: 23H06-7H06 offpeak_hours_5: 23H06-7H06 offpeak_hours_6: 23H06-7H06 plan: HC/HP production: "false" production_detail: "false" production_price: "0.0" production_max_date: 2021-06-01 production_detail_max_date: 2021-06-01 refresh_addresse: "false" refresh_contract: "false"
> 
> J'ai ce message depuis la dernière mise à jour, sans raison particulière est-ce une erreur de ma part ? Merci pour votre aide !

Merci de formater ton code la prochaine fois avec des quote ``` test ```.
Je pense que le soucis provient d'un soucis d'encodage entre ton Windows et ton conteneur, pense à faire un `dos2unis /path/to/config/file.yaml`.

**Comment by Mrsore** [comment]
Merci effectivement, problème d’encodage.
