### ISSUE TITLE
HassIO impossible d'installer la version 8.14

### ISSUE THREAD

**Issue by LGO44** [m4dm4rtig4n/myelectricaldata#322]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Impossible d'installer la version 8.14 depuis HACS adon
**Configuration**
Version installée 8.13
**Type d'installation**
 HassIO ?

**Version : 8.14*

Seule la version 8.13 apparait

**Comment by dudu7731** [comment]
Bonjour,

Il faut que le repo d'alexbelgium soit mis a jour pour être dispo sous hass.io.

d'où la latence entre la release sur github, docker et ensuite hassio addons (d'alexbelgium)

**Comment by m4dm4rtig4n** [comment]
Je n'ai effectivement pas la main sur cette partie, il faut voir ceci sur le repo d'@alexbelgium directement :
https://github.com/alexbelgium/hassio-addons/issues

**Comment by LGO44** [comment]
Merci

**Comment by alexbelgium** [comment]
Bonjour, en effet l'update automatique se fait les samedi. Vu que j'ai 78 add-ons en update, ça permet de tout faire en une fois. Et avoir une récurrence l'update plus faible limite la probabilité d'avoir un release boiteux qui sont remplacées le lendemain (par exemple sur certains add-ons qui ne publient que des versions tests comme jackett de mémoire)

Bonne journée

**Comment by LGO44** [comment]
Merci pour l'info, ce n'est pas un problème.

**Comment by dudu7731** [comment]
je profite de ce thread pour signaler un bug, suite a déploiement sur hass.io il y a un soucis de version : 
![image](https://user-images.githubusercontent.com/117290248/232191535-85c1e2fb-4cdc-4ba1-9a81-a1179866fd93.png)

**Comment by alexbelgium** [comment]
Mon addon pull `m4dm4rtig4n/myelectricaldata:latest`

**Comment by dudu7731** [comment]
coté hass.io on a la bonne version, dans les logs c'est aussi la bonne (8.15) a mon avis c'est juste un soucis de GUI, j'ai essayé de vider mon cache mais pas de changement.
![image](https://user-images.githubusercontent.com/117290248/232194808-f36f8eec-c24f-4722-9fdb-00ae8a98daf0.png)

```
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.15
 You are running the latest version of this add-on.

```

**Comment by pbranly** [comment]
Même bug mineur de mon côté

**Comment by LGO44** [comment]
Après installation de la version 8.15 , l'interface web n'affiche plus la version comme https://github.com/MyElectricalData/myelectricaldata/issues/322#issuecomment-1509587433
et n'affiche plus les points de livraison...

![image](https://user-images.githubusercontent.com/95585425/232233044-029e5cdd-6416-4936-8f9b-fd57696d61e8.png)
